export type FleetService = { slug: string; title: string; desc: string; tasks: readonly string[]; controls: readonly string[]; firstWeek: readonly string[] };
export type ResearchPost = { slug: string; title: string; excerpt: string; published: string; sections: readonly { heading: string; body: string }[]; sources?: readonly { name: string; url: string }[] };

export const fleetServices: readonly FleetService[] = [
  { slug: 'daily-transaction-coding', title: 'Daily Transaction Coding', desc: 'Build a Philippines-based daily transaction coding workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring bookkeeping work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'bank-reconciliation-support', title: 'Bank Reconciliation Support', desc: 'Build a Philippines-based bank reconciliation support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring bookkeeping work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'accounts-payable-processing', title: 'Accounts Payable Processing', desc: 'Build a Philippines-based accounts payable processing workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring bookkeeping work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'accounts-receivable-support', title: 'Accounts Receivable Support', desc: 'Build a Philippines-based accounts receivable support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring bookkeeping work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'payroll-journal-preparation', title: 'Payroll Journal Preparation', desc: 'Build a Philippines-based payroll journal preparation workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring bookkeeping work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'month-end-close-support', title: 'Month-End Close Support', desc: 'Build a Philippines-based month-end close support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring bookkeeping work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'management-reporting-support', title: 'Management Reporting Support', desc: 'Build a Philippines-based management reporting support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring bookkeeping work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'ecommerce-bookkeeping', title: 'Ecommerce Bookkeeping', desc: 'Build a Philippines-based ecommerce bookkeeping workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring bookkeeping work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'property-bookkeeping', title: 'Property Bookkeeping', desc: 'Build a Philippines-based property bookkeeping workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring bookkeeping work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'law-firm-bookkeeping', title: 'Law Firm Bookkeeping', desc: 'Build a Philippines-based law firm bookkeeping workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring bookkeeping work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] }
];

// Add reviewed, source-backed original research here. The templates and sitemap update automatically.
export const researchPosts: readonly ResearchPost[] = [];
export const postsPerPage = 20;
