import * as data from './data';
import { Header, Footer, JsonLd } from './components';
const d=data as any, site=d.site||{}, services=(d.services||[]).slice(0,6), posts=(d.blogPosts||[]).slice(0,3), stats=(d.stats||[]).slice(0,3), offer=d.staffingOffer||{};
const title=(x:any)=>typeof x==='string'?x:(x.title||x.name||x.label||x.question||'Role');
const text=(x:any)=>typeof x==='string'?x:(x.desc||x.excerpt||x.note||x.body||'Clear scope, review rhythm, and measurable handoff.');
const slug=(x:any)=>(x.slug||title(x).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,''));

export default function Home(){const schema={'@context':'https://schema.org','@type':'WebSite',name:site.brand,url:`https://${site.domain}`};return <><Header/><main className="adt"><JsonLd data={schema}/>
<section className="adt-hero"><div className="adt-container adt-grid"><div><p className="adt-eyebrow">Offshore bookkeeping support</p><h1>Build your offshore bookkeeping team.</h1><p>Get help with monthly close, AP, AR, reconciliations, and draft reports while your owner or controller keeps approval and final review.</p><div className="adt-actions"><a href="/contact">Plan my bookkeeping role</a><a href="#teams">See the work</a></div></div><div className="adt-team"><img src={site.serviceImage||site.heroImage} alt={site.alt||'bookkeeping team'}/><div className="adt-team-card"><b>Finance support team</b><span>Bookkeeper • AP • AR • Reviewer</span></div></div></div></section>
<section className="adt-why"><div className="adt-container"><p>A cleaner close starts with a clear handoff.</p><div className="adt-why-grid">{['Close calendar','Approval limits','Matched experience','Named reviewer','Useful task coverage','Evidence before sign-off'].map((x,i)=><article key={x}><span>{String(i+1).padStart(2,'0')}</span><b>{x}</b><p>{['Set due dates for source documents, reconciliations, questions, and draft reports.','Keep payments, payroll changes, write-offs, and final approval with the right person.','Look for bookkeepers who know your accounting software and type of work.','Give each exception and report one person who can answer or approve it.','Cover reconciliations, AP, AR, close support, and report preparation.','Attach statements, receipts, schedules, and notes so reviewers can check the work.'][i]}</p></article>)}</div></div></section>
<section className="adt-container adt-proof"><h2>Choose the work that belongs in the handoff.</h2><div className="adt-logos">{['Monthly close','Bank recs','AP support','AR aging','Draft reports','Exception log','Payroll records','Controller review'].map(x=><span key={x}>{x}</span>)}</div></section>
<section id="teams" className="adt-container adt-roles"><div><p className="adt-eyebrow">Teams we can build</p><h2>Start with one role or a small finance pod.</h2></div><div className="adt-role-grid">{[
  ['Bookkeeping Support','Transaction coding, receipt matching, bank-feed cleanup, and monthly checklist work.'],
  ['AP / AR Support','Vendor bill entry, invoice checks, aging notes, payment-prep support, and exception logs.'],
  ['Month-End Close Pod','Bank recs, payroll source docs, variance notes, close packets, and controller questions.'],
  ['Reporting & Review','Draft P&L, balance sheet notes, KPI summaries, evidence folders, and approval handoff.'],
].map(([name,copy],i)=><a href={services[i]?`/services/${slug(services[i])}`:'/contact'} key={name}><h3>{name}</h3><p>{copy}</p><b>See what the role covers →</b></a>)}</div></section>
<section className="adt-partner"><div className="adt-container adt-partner-grid"><div><h2>Plan the role before you hire.</h2><p>{offer.promise||'Set the task list, accounting tools, approval limits, and review owner before looking for a bookkeeper.'}</p></div><div>{(offer.included||[]).slice(0,4).map((x:string,i:number)=><article key={i}><span>✓</span><p>{x}</p></article>)}</div></div></section>
<section className="adt-container adt-guides"><h2>Bookkeeping guides</h2>{posts.map((p:any,i:number)=><a href={`/blog/${p.slug}`} key={i}><span>{p.minutes||7} min</span><b>{title(p)}</b><p>{text(p)}</p></a>)}</section>
</main><Footer/></>}
