import {notFound} from 'next/navigation';
import {Header,Footer,JsonLd} from '../../components';
import {getContent,getPost} from '../../../lib/content';
import {site} from '../../data';
const anchor=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,'-');
export function generateStaticParams(){return getContent('alternatives').map(post=>({slug:post.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const post=getPost('alternatives',slug);if(!post)return{};return{title:post.title,description:post.description,alternates:{canonical:`/alternatives/${slug}`},openGraph:{title:post.title,description:post.description,images:[post.featuredImage],type:'article'}}}
export default async function Alternative({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params,post=getPost('alternatives',slug);if(!post)notFound();const related=getContent('alternatives').filter(item=>item.slug!==slug).slice(0,3),base=`https://${site.domain.toLowerCase()}`,url=`${base}/alternatives/${slug}`;
  const schema={'@context':'https://schema.org','@graph':[{'@type':'Article',headline:post.title,description:post.description,datePublished:post.published,dateModified:post.updated,image:post.featuredImage,url},{'@type':'FAQPage',mainEntity:post.faqs.map(faq=>({'@type':'Question',name:faq.question,acceptedAnswer:{'@type':'Answer',text:faq.answer}}))},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:base},{'@type':'ListItem',position:2,name:'Alternatives',item:`${base}/alternatives`},{'@type':'ListItem',position:3,name:post.title,item:url}]}]};
  return <><Header/><main className="article-page"><JsonLd data={schema}/><article className="container article-layout"><div><header className="article-header"><p className="eyebrow">{post.competitor?'Competitor alternatives':post.type}</p><h1>{post.title}</h1><p className="lead">{post.description}</p></header><section className="article-card article-takeaways"><h2>Key takeaways</h2><ul>{post.takeaways.map(item=><li key={item}>{item}</li>)}</ul></section>{post.sections.map(section=><section className="article-card" id={anchor(section.heading)} key={section.heading}><h2>{section.heading}</h2>{section.body.split(/\n+/).map(p=><p key={p}>{p}</p>)}</section>)}<section className="article-card article-faq"><h2>Frequently asked questions</h2>{post.faqs.map(faq=><div key={faq.question}><h3>{faq.question}</h3><p>{faq.answer}</p></div>)}</section><section className="article-card"><h2>Related alternatives</h2>{related.length?<div className="related-three">{related.map(item=><a href={`/alternatives/${item.slug}`} key={item.slug}>{item.title}</a>)}</div>:<p>More comparisons are in editorial review.</p>}</section><aside className="article-banner"><div><h2>Build a controlled bookkeeping handoff</h2><span>Define the work, access, review, and exception ownership before hiring.</span></div><a href="/contact-us">Plan the role</a></aside></div><aside className="article-aside"><nav><b>On this page</b>{post.sections.map(section=><a href={`#${anchor(section.heading)}`} key={section.heading}>{section.heading}</a>)}</nav><a className="card consultation-card" href="/contact-us"><b>Compare your options</b><span>Bring your task list and review model.</span></a></aside></article></main><Footer/></>;
}
