import { notFound } from 'next/navigation';
import { Header, Footer, JsonLd } from '../../components';
import { getContent, getPost } from '../../../lib/content';
import { site } from '../../data';
const anchor=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,'-');
export function generateStaticParams(){ return getContent('research').map((post)=>({slug:post.slug})); }
export async function generateMetadata({params}:{params:Promise<{slug:string}>}) { const {slug}=await params; const post=getPost('research',slug); if(!post)return {}; return {title:post.title,description:post.description,alternates:{canonical:`/research/${slug}`},openGraph:{title:post.title,description:post.description,images:[post.featuredImage],type:'article'}}; }
export default async function ResearchArticle({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params; const post=getPost('research',slug); if(!post)notFound(); const related=getContent('research').filter((item)=>item.slug!==slug).slice(0,3); const base=`https://${site.domain.toLowerCase()}`,url=`${base}/research/${slug}`;
  const schema={'@context':'https://schema.org','@graph':[{'@type':'Article',headline:post.title,description:post.description,datePublished:post.published,dateModified:post.updated,image:post.featuredImage,url,citation:post.sources.map(s=>s.url)},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:base},{'@type':'ListItem',position:2,name:'Research',item:`${base}/research`},{'@type':'ListItem',position:3,name:post.title,item:url}]}]};
  return <><Header/><main className="article-page"><JsonLd data={schema}/><article className="container article-layout"><div><header className="article-header"><p className="eyebrow">{post.category}</p><h1>{post.title}</h1><p className="lead">{post.description}</p><span className="article-date">Verified {post.updated} · {post.sources.length} sources</span></header><section className="article-card article-takeaways"><h2>Key takeaways</h2><ul>{post.takeaways.map(item=><li key={item}>{item}</li>)}</ul></section>{post.sections.map((section)=><section className="article-card" id={anchor(section.heading)} key={section.heading}><h2>{section.heading}</h2>{section.body.split(/\n+/).map(p=><p key={p}>{p}</p>)}</section>)}<section className="article-card article-sources"><h2>Sources</h2><ol>{post.sources.map(source=><li key={source.url}><a href={source.url}>{source.name}</a></li>)}</ol></section><section className="article-card"><h2>Related research</h2>{related.length?<div className="related-three">{related.map(item=><a href={`/research/${item.slug}`} key={item.slug}>{item.title}</a>)}</div>:<p>More research is in editorial review.</p>}</section></div><aside className="article-aside"><nav><b>On this page</b>{post.sections.map(section=><a href={`#${anchor(section.heading)}`} key={section.heading}>{section.heading}</a>)}</nav><a className="card consultation-card" href="/contact-us"><b>Plan your finance workflow</b><span>Discuss scope, controls, and review ownership.</span></a></aside></article></main><Footer/></>;
}
