import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';

const source = path.join(process.cwd(), 'scripts', 'create_off73_research.mjs');
const temporary = path.join(process.env.PAPERCLIP_RUN_SCRATCH_DIR, 'create_off77_generated.mjs');
const topics = [
  {slug:'offshore-bookkeeping-ach-return-reconciliation-research', title:'How to study ACH return reconciliation', category:'Bank reconciliation', question:'whether ACH returns trace from bank notices and processor reports to customer or vendor subledgers, cash postings, and supported follow-up', unit:'one ACH return event for one payment, bank account, entity, and processing date', event:'a return that lacks a complete source-to-ledger trace or supported disposition by the approved cutoff', fields:'return ID, entity, bank account token, original payment ID, direction, amount, return code, bank date, ledger posting, subledger status, disposition, reviewer, and evidence link', groups:'entity, payment direction, return code family, amount band, bank account, disposition, and aging band', exceptions:'duplicate notices, partial returns, reversals, bank-file delays, processor netting, re-presentments, disputed payments, account changes, and cross-period postings', owner:'controller, treasury owner, or payments owner', link:'/services/bank-reconciliation-support'},
  {slug:'offshore-bookkeeping-payroll-garnishment-remittance-research', title:'How to study payroll garnishment remittance reconciliation', category:'Payroll bookkeeping', question:'whether authorized payroll garnishment deductions trace from payroll registers to liability balances, remittances, acknowledgments, and supported exceptions', unit:'one garnishment obligation, employee token, payroll, and remittance due event', event:'a deduction or liability that does not reconcile to authorized remittance evidence by the approved cutoff', fields:'obligation token, entity, employee token, authority, pay date, deduction amount, liability posting, due date, remittance date, confirmation reference, exception state, reviewer, and evidence link', groups:'entity, authority type, payroll frequency, amount band, remittance channel, exception reason, and aging band', exceptions:'new orders, releases, priority changes, protected earnings limits, retroactive corrections, employee transfers, voided payroll, rejected payments, and agency processing delays', owner:'payroll owner, legal counsel, or controller', link:'/services/month-end-close-support'},
  {slug:'offshore-bookkeeping-corporate-card-evidence-research', title:'How to study corporate-card transaction evidence coverage', category:'Expense bookkeeping', question:'whether corporate-card transactions have timely receipts, business-purpose records, coding support, approval evidence, and a traceable ledger posting', unit:'one posted corporate-card transaction for one card program, entity, and statement period', event:'a transaction that lacks one or more evidence elements required by the approved policy at cutoff', fields:'transaction ID, entity, card token, merchant, transaction date, posting date, amount, currency, receipt status, business purpose, coding, approval status, ledger posting, reviewer, and evidence link', groups:'entity, card program, merchant category, amount band, currency, evidence state, and aging band', exceptions:'credits, disputed charges, recurring subscriptions, split transactions, foreign exchange, personal reimbursements, card replacements, late receipts, and statement timing differences', owner:'controller, expense-policy owner, or authorized approver', link:'/services/month-end-close-support'},
  {slug:'offshore-bookkeeping-vendor-rebate-reconciliation-research', title:'How to study vendor rebate reconciliation', category:'Accounts payable', question:'whether earned vendor rebates trace from approved agreements and qualifying purchases to claims, credits, cash receipts, and ledger treatment', unit:'one vendor, rebate program, entity, and measurement period calculation', event:'a rebate calculation or receivable that cannot be reperformed from approved terms and complete purchase evidence at cutoff', fields:'program ID, entity, vendor token, period, eligible purchase base, tier, calculated rebate, claim date, credit or receipt reference, ledger posting, difference, reviewer, and evidence link', groups:'entity, program type, vendor segment, tier, amount band, settlement method, exception reason, and aging band', exceptions:'returns, exclusions, tier changes, amendments, cross-entity purchasing, volume true-ups, disputed eligibility, credits in transit, and foreign currency', owner:'controller, procurement owner, or contract owner', link:'/services/accounts-payable-processing'},
  {slug:'offshore-bookkeeping-inventory-obsolescence-evidence-research', title:'How to study inventory obsolescence evidence readiness', category:'Inventory bookkeeping', question:'whether inventory-aging, demand, condition, disposition, and approval records form a reproducible evidence packet for management’s obsolescence review', unit:'one inventory item, location, entity, and reporting-period review line', event:'a review line that lacks the approved source evidence or decision record needed to support its status at cutoff', fields:'item token, entity, location, quantity, carrying amount, last movement date, aging band, condition evidence, demand evidence, proposed status, authorized decision, ledger reference, reviewer, and evidence link', groups:'entity, location, product family, aging band, amount band, evidence status, proposed disposition, and exception reason', exceptions:'seasonal stock, new launches, safety stock, bundled items, returns, damaged goods, consignment, transfers in transit, discontinued products, and post-cutoff sales', owner:'controller, inventory owner, or authorized accounting-policy owner', link:'/services/management-reporting-support'},
];

let code = fs.readFileSync(source, 'utf8')
  .replace("const date = '2026-09-23';", "const date = '2026-09-25';")
  .replace(/const displayDate = '[^']+';/, "const displayDate = 'September 25, 2026';")
  .replace(/const topics = \[[\s\S]*?\n\];\n\nfunction article/, `const topics = ${JSON.stringify(topics, null, 2)};\n\nfunction article`)
  .replace('research-off73.json', 'research-off77.json');
fs.writeFileSync(temporary, code);
const result = spawnSync(process.execPath, [temporary], { cwd: process.cwd(), stdio: 'inherit' });
if (result.status !== 0) process.exit(result.status ?? 1);
