import fs from 'node:fs';
import crypto from 'node:crypto';

const date = '2026-10-02';
const baseline = '449c1417515efa78bd989d5aaf28393b467a38b8';
const image = '/thumbnails/bookkeeping-monthly-review-meeting-agenda.webp';

const topics = [
  {slug:'offshore-bookkeeping-home-services-warranty-callback-costs', title:'Track home-services warranty callbacks without distorting job margin', category:'Home services bookkeeping', subject:'warranty callback costs', source:'completed work orders, technician return visits, parts issues, customer complaints, and the original invoice', unit:'service job and callback reason', exception:'a return visit that combines warranty work with a new billable request', example:'an HVAC installer returns to replace a failed control board under its workmanship promise while also adding a customer-requested thermostat', decision:'whether the cost belongs to the original job, a vendor recovery, a current-period service expense, or new billable work'},
  {slug:'offshore-bookkeeping-manufacturing-customer-tooling-deposits', title:'Reconcile customer tooling deposits from quote to production approval', category:'Manufacturing bookkeeping', subject:'customer tooling deposits', source:'customer quote, tooling purchase order, supplier invoice, acceptance milestone, customer billing, and cash receipt', unit:'tool identifier and customer program', exception:'a tool used across several products or retained by the manufacturer after the program ends', example:'a fabricator collects a deposit for a dedicated die, pays the toolmaker in stages, and receives customer approval after sample parts pass inspection', decision:'whether each amount is a refundable deposit, deferred revenue, reimbursable cost, owned asset, or earned charge under the agreement'},
  {slug:'offshore-bookkeeping-franchise-marketing-fund-ledger', title:'Build a franchise marketing-fund ledger that separates collections and spend', category:'Franchise bookkeeping', subject:'franchise marketing-fund activity', source:'franchise agreements, location sales reports, assessment invoices, receipts, campaign approvals, vendor bills, and allocation schedules', unit:'franchise location, campaign, and assessment period', exception:'a corporate campaign that benefits both company-owned and franchised locations', example:'a franchisor collects two monthly assessments, prepays an annual media package, and later issues a credit to a location whose reported sales were corrected', decision:'how collections, restricted or designated spending, prepayments, credits, and corporate contributions should be presented and supported'},
  {slug:'offshore-bookkeeping-hotel-ota-commission-accrual', title:'Accrue hotel OTA commissions from guest stay to platform statement', category:'Hospitality bookkeeping', subject:'online travel agency commission accruals', source:'reservation ledger, stay dates, folio revenue, cancellation record, OTA contract, commission invoice, and platform statement', unit:'reservation and completed stay', exception:'a no-show, cancellation, or modified booking whose commission treatment differs from the original reservation', example:'a guest shortens a four-night stay after check-in while the OTA statement still calculates commission on the original booking value', decision:'which completed stays create commission cost, what estimate remains open, and when invoice differences require correction'},
  {slug:'offshore-bookkeeping-childcare-enrollment-deposit-rollforward', title:'Roll forward childcare enrollment deposits through placement, refund, and forfeiture', category:'Childcare bookkeeping', subject:'childcare enrollment deposits', source:'family agreement, wait-list record, placement offer, payment receipt, enrollment date, withdrawal notice, refund approval, and bank settlement', unit:'child, program, and deposit receipt', exception:'siblings whose deposits are transferred between programs or enrollment terms', example:'a family pays for an infant opening, moves the start date twice, then applies part of the deposit to the first tuition invoice under the signed policy', decision:'whether the balance remains refundable, applies to tuition, becomes an approved forfeiture, or must be returned'},
  {slug:'offshore-bookkeeping-saas-usage-billing-true-up', title:'Reconcile SaaS usage billing true-ups before invoices reach customers', category:'SaaS bookkeeping', subject:'usage-based billing true-ups', source:'contract terms, meter export, account hierarchy, pricing tier, included allowance, billing run, credit memo, and general ledger detail', unit:'customer, subscription, meter, and billing period', exception:'late usage events that arrive after an invoice has been finalized', example:'an API customer crosses a volume tier, receives a contractual allowance, and sends corrected usage after the monthly invoice was issued', decision:'which usage is billable now, deferred to a later bill, credited, disputed, or excluded under the contract'},
  {slug:'offshore-bookkeeping-dental-lab-fee-accrual', title:'Accrue dental lab fees by case instead of guessing from monthly invoices', category:'Dental bookkeeping', subject:'dental laboratory fee accruals', source:'patient case log, lab slip, shipment record, procedure status, remakes, vendor statement, invoice, and credit memo', unit:'patient case and laboratory order', exception:'a remake performed without charge or a case abandoned before final placement', example:'a practice receives a crown before month end, seats it in the following month, and later receives a lab invoice that includes a no-charge remake', decision:'when the practice incurred the lab obligation, which case owns the cost, and whether a later credit changes the estimate'},
  {slug:'offshore-bookkeeping-software-implementation-cost-intake', title:'Organize software implementation costs for a documented accounting review', category:'Technology bookkeeping', subject:'software implementation cost intake', source:'vendor statement of work, internal project plan, time record, invoice line, change order, go-live evidence, and approval', unit:'implementation project, workstream, and cost line', exception:'an invoice that combines data migration, training, configuration, support, and subscription access', example:'a company pays one vendor for configuration and user training while employees also clean data and test integrations before launch', decision:'which facts the accounting reviewer needs to distinguish operating expense, prepayment, or a cost that may require capitalization analysis'},
  {slug:'offshore-bookkeeping-agriculture-harvest-inventory-cost-pack', title:'Prepare a harvest inventory cost pack from field activity to saleable lots', category:'Agriculture bookkeeping', subject:'harvest inventory cost evidence', source:'field log, harvest ticket, labor record, packing report, storage statement, spoilage log, lot transfer, and sales record', unit:'crop, field, harvest date, and saleable lot', exception:'mixed lots or by-products created during grading and packing', example:'a grower harvests two fields into one packing run, loses a measured quantity to spoilage, and stores the remaining graded lots for later sale', decision:'how documented quantities and approved cost pools move from growing activity into packed inventory and cost of sales'},
  {slug:'offshore-bookkeeping-event-venue-deposit-forfeiture', title:'Account for event-venue deposits when bookings change or cancel', category:'Events bookkeeping', subject:'event venue deposits', source:'signed event agreement, payment schedule, booking calendar, cancellation notice, rescheduling amendment, refund approval, and bank activity', unit:'event booking and contracted date', exception:'a cancellation converted into a credit for a future event rather than cash refund', example:'a client cancels a reception after the refund window, negotiates a partial future-date credit, and receives the remaining approved refund', decision:'what remains a customer liability, what transfers to a new booking, what is refunded, and when any retained amount becomes earned'},
  {slug:'offshore-bookkeeping-coworking-access-key-deposit-register', title:'Reconcile coworking access-key deposits across member moves and exits', category:'Coworking bookkeeping', subject:'coworking access-key deposits', source:'membership agreement, access-control issue log, deposit receipt, location transfer, key return record, damage charge, refund approval, and bank activity', unit:'member, location, and issued access credential', exception:'a member who transfers locations while retaining one credential and receiving another', example:'a member moves from a shared desk to a private office, receives two new keys, returns one old card, and is charged for a missing fob at final exit', decision:'which receipts remain refundable liabilities, which transfer between locations, which approved charges reduce a refund, and what cash must be returned'},
  {slug:'offshore-bookkeeping-shipping-insurance-claim-recovery', title:'Track shipping insurance claims from lost parcel to final recovery', category:'Ecommerce bookkeeping', subject:'shipping insurance claim recoveries', source:'sales order, carrier scan, proof of value, customer refund or replacement, claim submission, carrier decision, and settlement advice', unit:'shipment, customer order, and claim number', exception:'a partial recovery that excludes freight, tax, or the full merchandise value', example:'an ecommerce seller replaces a lost order immediately, files a carrier claim, and receives a settlement weeks later for less than the recorded fulfillment cost', decision:'how to connect the customer remedy, inventory movement, carrier receivable, fees, denial, and final recovery without netting unrelated amounts'},
];

function body(t) {
return `${t.subject[0].toUpperCase()+t.subject.slice(1)} create a bookkeeping problem because operational facts and accounting events rarely arrive together. A payment may precede delivery, a vendor document may arrive after close, or an operational status may change after an invoice is posted. An offshore bookkeeper can keep those facts organized without making the commercial or accounting decisions that belong to management. The useful output is a traceable workpaper: one row per ${t.unit}, linked to evidence and routed to the right reviewer.

This workflow is designed for a controller or owner who wants repeatable preparation rather than a month-end search through email. It shows what the preparer can collect, how to test completeness, which exceptions deserve attention, and where approval must remain with the client. It does not prescribe an accounting policy. The applicable contract, facts, materiality, and professional advice determine the final treatment.

## Define the population before calculating a balance

Start with a source population, not the general-ledger total. For ${t.subject}, the core evidence usually includes ${t.source}. Choose a consistent cutoff and document the system filters, entity, timezone, and status fields used. Save the raw export or report reference so another reviewer can reproduce the population later.

The tracking key should be the ${t.unit}. Do not rely only on a customer or vendor name, because one counterparty may have many open events with different terms. Record the original date, relevant service or delivery date, amount, currency, operational status, ledger account, document links, and last update. If the source system changes identifiers, keep both the old and new references rather than overwriting the history.

Completeness deserves its own check. Compare the source count and amount with an independent control, such as cash receipts, sequential documents, a subledger total, or an operating report. Explain excluded statuses explicitly. A neat schedule is not complete merely because its columns add correctly.

## Translate the agreement into reviewable fields

The bookkeeper should extract the terms that drive timing and classification into structured fields. For this topic, the central question is ${t.decision}. Capture the relevant trigger, refund or credit terms, approval requirement, ownership language, service period, and any cap or exclusion. Link each extracted term to the signed agreement or approved policy version.

Avoid asking a preparer to interpret vague language silently. If two clauses point to different outcomes, flag the conflict and quote only the short operative wording needed by the reviewer. Record the question, named decision owner, due date, and response. The approved answer should update the workpaper without deleting the earlier question, because that history explains why the entry was prepared.

Use controlled status values rather than free-form labels. A practical set might include awaiting evidence, ready for review, approved for posting, posted, disputed, and closed. Topic-specific sub-statuses can be added when they change the next action. Definitions belong in the procedure so two preparers do not use the same status differently.

## Build the rollforward at the transaction level

Create an opening-to-closing bridge. Begin with the prior approved balance, add current-period items supported by the source population, subtract settlements or releases, separate reclassifications, and arrive at the proposed ending balance. Every movement needs a document reference and posting reference. Differences should remain visible in an exception column instead of being forced into an unexplained plug.

For ${t.subject}, organize movements by the ${t.unit}. Include gross amounts before netting where different economic events are involved. That makes it possible to distinguish a receipt from a refund, an invoice from a credit, or a cost from a recovery. If the accounting system posts net cash, retain a settlement bridge that connects gross components to the bank amount.

Age unresolved items from the date the next action first became due, not from the date someone last edited the spreadsheet. Preserve the original age when an item rolls into a new period. Add an owner, next action, evidence needed, and target resolution date. Aging turns the schedule into an operating queue and prevents old questions from appearing new each month.

## Test the difficult exception instead of hiding it

A recurring edge case is ${t.exception}. Give that case a separate review path. Split the components, retain the supporting correspondence, and identify which fact remains uncertain. Do not apply the most convenient treatment to the entire amount simply because the system produced one line.

The exception log should state the observed condition, affected amount, source references, current ledger treatment, proposed options, and approval owner. Use factual language. “Contract amendment not received” is more useful than “probably deferred.” If a deadline matters, state who owns it and what will happen operationally if no answer arrives; do not invent an accounting conclusion to clear the queue.

Recurring exceptions signal a process problem. Tag root causes such as missing identifier, late operational update, inconsistent contract data, duplicate submission, cutoff mismatch, or unrecorded credit. Trend the tags only after their definitions are stable. Management can then decide whether to change an upstream form, integration, approval rule, or vendor process.

## Work through a concrete example

Consider this situation: ${t.example}. The offshore bookkeeper first creates the ${t.unit} record and attaches each available source. The preparer separates cash, invoice, operational completion, and later adjustment rather than recording one net number. Next, the preparer marks the disputed or judgmental component and sends a bounded question to the designated reviewer.

The example should produce at least three auditable outputs: a population row, a rollforward movement, and an exception record. When management approves the treatment, the bookkeeper records the approval reference, prepares the authorized entry or system update, and then verifies the resulting ledger balance. If new evidence arrives later, it becomes a dated follow-up movement; it does not rewrite the original evidence trail.

This approach also improves customer and vendor communication. Staff can see whether the business is waiting for a document, an approval, a system correction, or an external settlement. They do not need to infer status from a general-ledger balance. The accounting reviewer can focus on the limited set of decisions rather than reconstructing every transaction.

## Reconcile source, subledger, ledger, and cash

Use a four-way comparison when the systems permit it. The operational source proves the event and status. The subledger shows the billing, payable, deposit, or claim record. The general ledger shows financial classification. The bank or processor evidence confirms cash movement. Differences between these layers should have named explanations and owners.

Run mechanical tests before review: duplicate identifiers, missing dates, impossible status combinations, negative amounts where not expected, stale open items, missing approval references, and totals that do not match control reports. A formula check cannot prove the business event, but it can keep avoidable errors out of the review queue.

Tie the ending schedule to the exact ledger account, entity, period, and currency. When several accounts are involved, show a mapping table. Save the ledger report parameters and posting references. If foreign currency is relevant, retain both transaction and functional-currency amounts plus the approved rate source; do not bury exchange movement in an operational variance.

## Set a clear offshore preparation boundary

An offshore bookkeeper can maintain the register, collect and index evidence, run duplicate and completeness tests, prepare the rollforward, draft factual questions, and post entries after documented approval. The client should retain contract interpretation, policy selection, materiality decisions, estimates, write-offs, dispute strategy, and final approval. Access should be limited to the systems and fields required for the assigned work.

Design the handoff around exceptions. A reviewer packet should contain the control totals, proposed ending balance, unresolved items ranked by age or amount, decisions requested, and links to source evidence. Record the review date and reviewer, then verify that approved actions reached the ledger and related operational system. Closure means the source, approval, posting, and final balance agree—not merely that a comment was marked resolved.

[Bookkeeping services](/services/bookkeeping) can support the recurring preparation and evidence discipline, while [management reporting support](/services/management-reporting-support) can help carry approved results into a controlled review packet. The company’s management and advisers remain responsible for policy and judgment.

## Keep the procedure durable across periods

At period end, archive the source extracts, workpaper version, approval evidence, posting report, and exception list together. Carry unresolved items forward with their original dates. Update the procedure only through a versioned change that names the reason, effective period, and approver. This prevents a new team member from unknowingly applying a changed rule to old transactions.

Finally, review whether the workflow is producing useful decisions. Track missing-source frequency, exception age, reopenings, and adjustments after review. These are process indicators, not performance claims. Used carefully, they show where documentation or ownership needs attention and make ${t.subject} easier to supervise without removing the client’s control over consequential decisions.`;
}

const articles=[];
for (const t of topics) {
  const content = `---\ntitle: ${JSON.stringify(t.title)}\ndescription: ${JSON.stringify(`A practical offshore bookkeeping workflow for ${t.subject}, evidence, exceptions, review, and handoff.`)}\npublished: ${JSON.stringify(date)}\nupdated: ${JSON.stringify(date)}\ncategory: ${JSON.stringify(t.category)}\ntype: "blog"\nfeaturedImage: ${JSON.stringify(image)}\ntakeaways: ${JSON.stringify([`Build the population around each ${t.unit}.`,`Keep exceptions visible until evidence and approval agree.`,`Separate offshore preparation from client accounting judgment.`])}\nsources: ${JSON.stringify([{name:'U.S. Small Business Administration, Manage your finances',url:'https://www.sba.gov/business-guide/manage-your-business/manage-your-finances'},{name:'IRS, Recordkeeping',url:'https://www.irs.gov/businesses/small-businesses-self-employed/recordkeeping'}])}\nrelatedLinks: ${JSON.stringify([['Bookkeeping services','/services/bookkeeping'],['Management reporting support','/services/management-reporting-support']])}\nfaqs: ${JSON.stringify([[`Can an offshore bookkeeper maintain the ${t.subject} schedule?`,'Yes. The preparer can maintain evidence, reconciliations, and exception questions while the client retains policy choices and approvals.'],['What should each row identify?',`At minimum, identify the ${t.unit}, dates, amounts, status, evidence, ledger mapping, owner, and next action.`],['When should an item be closed?','Close it only after the approved action is posted and the source, ledger, and settlement evidence agree.']])}\n---\n\n${body(t)}\n`;
  const sourcePath=`content/blog/${t.slug}.md`;
  fs.writeFileSync(sourcePath,content);
  const hash=crypto.createHash('sha256').update(content).digest('hex');
  articles.push({family:'blog',topic:t.title,slug:t.slug,sourcePath,featuredImage:image,sources:['https://www.sba.gov/business-guide/manage-your-business/manage-your-finances','https://www.irs.gov/businesses/small-businesses-self-employed/recordkeeping'],contentHash:hash,publicationDate:date,liveUrl:`https://offshorebookkeepers.com/blog/${t.slug}`});
}
fs.mkdirSync(`.paperclip/daily-content/${date}`,{recursive:true});
fs.writeFileSync(`.paperclip/daily-content/${date}/blog-off-82.json`,JSON.stringify({task:'OFF-82',cycle:date,baseline,status:'draft-local',timezone:'UTC',articles},null,2)+'\n');
console.log(`wrote ${articles.length} Blog articles`);
