import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';

const source = path.join(process.cwd(), 'scripts', 'create_off73_research.mjs');
const temporary = path.join(process.env.PAPERCLIP_RUN_SCRATCH_DIR, 'create_off76_generated.mjs');
const topics = [
  {slug:'offshore-bookkeeping-loan-schedule-ledger-reconciliation-research', title:'How to study loan-schedule-to-ledger reconciliation', category:'Month-end close', question:'whether loan principal, interest, fees, and ending balances agree between lender evidence, the approved amortization schedule, and the general ledger', unit:'one loan, reporting period, and currency reconciliation', event:'a loan-period reconciliation that contains an unexplained difference or lacks evidence of review by the cutoff', fields:'loan token, entity, lender statement date, currency, opening balance, proceeds, principal paid, interest paid, fees, ending balance, ledger accounts, difference, reviewer, and evidence link', groups:'entity, facility type, currency, amount band, difference type, payment status, and aging band', exceptions:'variable rates, refinancings, payment holidays, lender fees, accrued interest, foreign exchange, debt modifications, late statements, and current-versus-long-term reclassifications', owner:'controller, treasury owner, or CPA', link:'/services/month-end-close-support'},
  {slug:'offshore-bookkeeping-gift-card-liability-rollforward-research', title:'How to study gift-card liability rollforwards', category:'E-commerce bookkeeping', question:'whether gift-card sales, redemptions, refunds, expirations, and closing liabilities form a traceable rollforward across commerce, payment, and ledger systems', unit:'one gift-card program, entity, currency, and reporting period', event:'a period rollforward that fails its approved source-to-ledger tie-out or contains an unsupported adjustment at cutoff', fields:'program ID, entity, currency, opening liability, cards issued, cash collected, redemptions, refunds, expirations, manual adjustments, closing liability, ledger balance, reviewer, and evidence link', groups:'entity, channel, currency, program, adjustment type, amount band, and exception age', exceptions:'promotional cards, partial redemptions, refunds to cards, multi-currency use, platform migrations, expirations, breakage estimates, duplicate events, and delayed settlement files', owner:'controller or authorized accounting-policy owner', link:'/services/bank-reconciliation-support'},
  {slug:'offshore-bookkeeping-franchise-royalty-source-reconciliation-research', title:'How to study franchise royalty source reconciliation', category:'Multi-location bookkeeping', question:'whether royalty and marketing-fee calculations trace from approved agreements and location sales reports to invoices, collections, and ledger postings', unit:'one location, fee type, and reporting period calculation', event:'a fee calculation or posting that cannot be reperformed from approved terms and complete source sales at cutoff', fields:'location token, entity, period, fee type, approved rate, sales base, exclusions, calculated fee, billed amount, collected amount, ledger posting, reviewer, and evidence link', groups:'entity, location cohort, fee type, sales-source system, amount band, exception reason, and aging band', exceptions:'new locations, closures, amended agreements, tiered rates, excluded sales, late sales reports, refunds, currency conversion, manual invoices, and disputed fees', owner:'controller, franchise accounting owner, or contract owner', link:'/services/management-reporting-support'},
  {slug:'offshore-bookkeeping-unclaimed-property-evidence-handoff-research', title:'How to study unclaimed-property evidence handoffs', category:'Accounts payable', question:'whether stale checks, customer credits, payroll items, and other candidate balances are identified, researched, and routed with evidence before jurisdiction-specific decisions are due', unit:'one candidate property record for one owner, property type, entity, and jurisdiction review', event:'a candidate record that lacks the evidence or authorized disposition required by the approved review calendar', fields:'candidate ID, entity, property type, owner token, last activity date, amount, currency, address state, source account, outreach status, disposition, decision owner, and evidence link', groups:'entity, property type, jurisdiction, amount band, source account, disposition, and aging band', exceptions:'returned checks, disputed balances, active vendors, duplicate owners, foreign addresses, payroll items, credits applied after extraction, voids, reissues, and legal holds', owner:'controller, legal counsel, payroll owner, or unclaimed-property specialist', link:'/services/accounts-payable-processing'},
  {slug:'offshore-bookkeeping-workers-compensation-payroll-audit-evidence-research', title:'How to study workers’ compensation payroll-audit evidence readiness', category:'Payroll bookkeeping', question:'whether payroll classifications, wages, exclusions, locations, and supporting reports can be reconciled into a reviewable evidence packet for an insurer audit', unit:'one worker classification, location, entity, and policy-period payroll summary', event:'a summary line that does not reconcile to approved payroll records or lacks support for its classification or exclusion at cutoff', fields:'worker token, entity, work state, class code, pay type, gross wages, included wages, excluded wages, policy period, payroll report reference, reconciliation status, reviewer, and evidence link', groups:'entity, work state, class code, pay type, location, exception reason, and evidence status', exceptions:'multi-state work, overtime treatment, officer elections, subcontractors, bonuses, tips, severance, payroll corrections, policy changes, and missing certificates', owner:'payroll owner, risk manager, broker, insurer, or qualified adviser', link:'/services/month-end-close-support'},
];

let code = fs.readFileSync(source, 'utf8')
  .replace(/const date = '\d{4}-\d{2}-\d{2}';/, "const date = '2026-09-24';")
  .replace(/const displayDate = '[^']+';/, "const displayDate = 'September 24, 2026';")
  .replace(/const topics = \[[\s\S]*?\n\];\n\nfunction article/, `const topics = ${JSON.stringify(topics, null, 2)};\n\nfunction article`)
  .replace("research-off73.json", "research-off76.json");
fs.writeFileSync(temporary, code);
const result = spawnSync(process.execPath, [temporary], { cwd: process.cwd(), stdio: 'inherit' });
if (result.status !== 0) process.exit(result.status ?? 1);
