import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';

const source = path.join(process.cwd(), 'scripts', 'create_off73_research.mjs');
const temporary = path.join(process.env.PAPERCLIP_RUN_SCRATCH_DIR, 'create_off79_generated.mjs');
const topics = [
  {slug:'offshore-bookkeeping-payment-processor-reserve-research',title:'How to study payment-processor reserve reconciliation',category:'Ecommerce bookkeeping',question:'whether processor reserves trace from settlement terms and withheld amounts to releases, deductions, cash receipts, and ledger balances',unit:'one processor reserve movement for one merchant account, entity, currency, and settlement date',event:'a withheld, adjusted, or released amount that cannot be traced through the processor statement, bank evidence, and ledger at cutoff',fields:'processor event ID, merchant account token, entity, currency, transaction date, reserve basis, withheld amount, release date, deductions, cash receipt, ledger account, reviewer, and evidence link',groups:'processor, entity, currency, reserve reason, age band, release state, amount band, and mismatch cause',exceptions:'rolling reserves, fixed reserves, chargebacks, refunds, fees, currency conversion, negative settlements, account migrations, release delays, and contract changes',owner:'controller, treasury owner, or ecommerce finance owner',link:'/services/ecommerce-bookkeeping'},
  {slug:'offshore-bookkeeping-deferred-revenue-contract-change-research',title:'How to study deferred-revenue contract-change evidence',category:'Revenue bookkeeping',question:'whether contract amendments reach the billing record, revenue schedule, general ledger, and management review with a complete decision trail',unit:'one approved customer-contract amendment affecting one revenue schedule',event:'an amendment whose economic terms, effective date, schedule effect, or approval cannot be reperformed from retained evidence at cutoff',fields:'contract token, customer token, entity, amendment date, effective date, changed terms, billing effect, schedule version, ledger effect, decision owner, reviewer, and evidence link',groups:'entity, amendment type, billing model, effective-date band, amount band, schedule state, and exception reason',exceptions:'renewals, cancellations, scope additions, concessions, credits, usage true-ups, currency changes, bundled items, retrospective edits, and unsigned drafts',owner:'controller or authorized revenue-policy owner',link:'/services/month-end-close-support'},
  {slug:'offshore-bookkeeping-loan-covenant-input-lineage-research',title:'How to study loan-covenant input lineage',category:'Management reporting',question:'whether every bookkeeping input used in a lender covenant calculation is tied to a closed ledger, approved adjustment, definition source, and review record',unit:'one covenant input line for one agreement, entity group, and test date',event:'an input that lacks an unbroken trace from agreement definition through source balance and adjustment to the submitted calculation',fields:'agreement token, covenant name, test date, definition reference, entity scope, source account, ledger period, adjustment ID, calculated input, reviewer, approval, and evidence link',groups:'agreement, covenant, entity scope, input class, adjustment type, amount band, evidence state, and review outcome',exceptions:'amendments, waivers, acquisitions, disposals, pro forma adjustments, foreign exchange, trailing-period measures, restricted cash, classifications, and post-close journals',owner:'CFO, controller, treasury owner, or legal counsel',link:'/services/management-reporting-support'},
  {slug:'offshore-bookkeeping-marketplace-facilitator-evidence-research',title:'How to study marketplace-facilitator sales-tax evidence',category:'Sales tax bookkeeping',question:'whether marketplace-collected tax is separated from seller-collected tax using jurisdiction, order, facilitator, settlement, filing, and ledger evidence',unit:'one marketplace order tax component for one seller entity and destination jurisdiction',event:'a tax component whose collection responsibility or ledger disposition is unsupported or inconsistent across marketplace and bookkeeping records',fields:'order token, seller entity, marketplace, destination jurisdiction, order date, taxable base, tax amount, collector indicator, settlement reference, ledger mapping, filing treatment, reviewer, and evidence link',groups:'marketplace, entity, jurisdiction, product tax class, collector state, filing treatment, amount band, and exception reason',exceptions:'returns, partial refunds, mixed baskets, marketplace credits, direct-channel orders, exemption records, destination changes, settlement netting, registration changes, and amended filings',owner:'tax adviser, controller, or authorized compliance owner',link:'/services/sales-tax-support'},
  {slug:'offshore-bookkeeping-capital-project-commitment-research',title:'How to study capital-project commitment completeness',category:'Fixed assets',question:'whether approved purchase orders, contracts, change orders, invoices, accruals, and cancellations produce a complete project-commitment view',unit:'one commitment component for one authorized capital project and reporting cutoff',event:'an open, changed, consumed, or cancelled commitment that does not reconcile between procurement evidence, project records, and the ledger',fields:'project token, entity, authorization ID, vendor token, purchase order, contract value, change order, invoiced amount, accrued amount, cancellation, remaining commitment, reviewer, and evidence link',groups:'entity, project phase, commitment source, vendor class, amount band, age band, change status, and exception reason',exceptions:'unissued purchase orders, verbal changes, retainage, deposits, disputed invoices, foreign currency, partial cancellations, shared contracts, transferred projects, and closeout costs',owner:'controller, project owner, or capital-approval authority',link:'/services/management-reporting-support'},
];

let code = fs.readFileSync(source, 'utf8')
  .replace("const date = '2026-09-23';", "const date = '2026-09-28';")
  .replace(/const displayDate = '[^']+';/, "const displayDate = 'September 28, 2026';")
  .replace(/const topics = \[[\s\S]*?\n\];\n\nfunction article/, `const topics = ${JSON.stringify(topics, null, 2)};\n\nfunction article`)
  .replace('research-off73.json', 'research-off79.json');
fs.writeFileSync(temporary, code);
const result = spawnSync(process.execPath, [temporary], {cwd:process.cwd(),stdio:'inherit'});
if (result.status !== 0) process.exit(result.status ?? 1);
