import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(new URL('..', import.meta.url).pathname);
const topics = [
 ['offshore-bookkeeping-cash-application-policy','How an offshore bookkeeper can support a cash application policy','cash application','unapplied receipts and customer remittances','match remittance evidence to open invoices while leaving disputed or unusual applications for an authorized reviewer'],
 ['offshore-bookkeeping-close-calendar-owner-map','How to map close-calendar ownership for an offshore bookkeeping team','close-calendar ownership','period-end deadlines and handoffs','turn a close calendar into named preparation, review, and decision lanes instead of treating every task as interchangeable'],
 ['offshore-bookkeeping-ap-accrual-evidence','How offshore bookkeeping support can organize AP accrual evidence','AP accrual evidence','unbilled goods, services, and cutoff support','assemble a traceable accrual packet from receiving, purchase, and vendor evidence without inventing an accounting estimate'],
 ['offshore-bookkeeping-ar-dispute-register','How to run an AR dispute register with offshore bookkeeping support','AR dispute management','short-paid invoices and customer claims','separate collection activity, evidence gathering, and credit decisions so disputes do not disappear inside an ageing report'],
 ['offshore-bookkeeping-payroll-variance-review','How an offshore bookkeeper can prepare a payroll variance review','payroll variance review','changes in headcount, earnings, deductions, and clearing accounts','compare approved payroll inputs with the ledger and route unexplained movements without making payroll or employment decisions'],
 ['offshore-bookkeeping-inventory-count-reconciliation','How offshore bookkeeping support can reconcile an inventory count','inventory count reconciliation','count sheets, receiving records, and ledger quantities','document count differences and cutoff facts so an operations owner can decide on adjustments and investigation'],
 ['offshore-bookkeeping-lease-data-handoff','How to build a lease-data handoff for an offshore bookkeeping team','lease data handoff','contracts, amendments, and recurring payment schedules','maintain a controlled lease information packet while reserving classification and accounting conclusions for the responsible finance professional'],
 ['offshore-bookkeeping-chart-of-accounts-change-log','How an offshore bookkeeper can maintain a chart-of-accounts change log','chart-of-accounts governance','new accounts, renamed accounts, and mapping changes','record who requested a ledger structure change, what reports it affects, and what approval is still required'],
 ['offshore-bookkeeping-foreign-currency-revaluation-pack','How offshore bookkeeping support can prepare a foreign-currency revaluation pack','foreign-currency close support','rate evidence, balances, and remeasurement inputs','prepare a reproducible currency workpaper while keeping rate selection and material accounting judgments with the authorized reviewer'],
 ['offshore-bookkeeping-project-margin-bridge','How to prepare a project-margin bridge with offshore bookkeeping support','project margin analysis','labor, vendor cost, billing, and forecast changes','explain movement between two project views using source-backed buckets rather than presenting a misleading single variance number'],
 ['offshore-bookkeeping-employee-onboarding-ledger','How an offshore bookkeeper can control an employee-onboarding ledger','employee onboarding records','start dates, pay setup evidence, reimbursements, and access requests','track administrative completeness without approving compensation, benefits, access, or employment terms'],
 ['offshore-bookkeeping-monthly-kpi-definition','How to define a monthly KPI packet for offshore bookkeeping support','monthly KPI definitions','close status, ageing, rework, and unresolved decisions','make management reporting consistent by defining each measure, its source, its owner, and the action it should trigger']
];
const unique = [
 'Begin with the boundary. A Philippines-based bookkeeper can prepare, compare, classify observable facts, and maintain a workpaper when the written procedure permits it. The business owner, controller, or other authorized reviewer keeps approval, policy interpretation, payment release, tax positions, and unusual accounting decisions. Writing that boundary into the task prevents a fast queue from becoming an uncontrolled decision channel.',
 'The useful unit of work is not a vague request such as “clean this up.” It is a record with an identifier, source location, period, preparer, status, next action, and named owner. When a reviewer opens the item later, the reviewer should be able to see what was known at the time, what was checked, and what remains uncertain. That makes remote handoffs auditable without pretending that documentation replaces judgment.',
 'Set the population before measuring performance. State which accounts, entities, dates, and transaction types are included; note exclusions; and preserve the extraction date. If a source system changes, keep the prior population and explain the difference. A bookkeeper may assemble the list, but the accountable finance lead should approve the definition of completeness because a missing population can make every downstream metric look healthy.',
 'Use evidence in layers. Start with the primary record, then connect supporting documents, system notes, correspondence, and prior-period context. Record links or stable filenames rather than relying on memory. If evidence conflicts, describe the conflict plainly and stop at the permitted step. A proposed treatment is not an approved treatment, and a similar-looking item is not proof that two transactions belong together.',
 'Design the review queue around decisions, not merely statuses. “Open” says little; “owner to confirm whether the receipt belongs to invoice 1842 by close-day two” gives a reviewer something answerable. Include the question, options if policy allows them, evidence already checked, and consequence of delay. This is especially important across time zones, where an unclear message can consume a full working day before it is corrected.',
 'Protect the source trail. Never overwrite an imported amount, date, vendor, customer, or employee reference with a convenient correction. Put the proposed value in a separate field and retain the original. Use named accounts, multifactor authentication, least-privilege access, and a controlled workspace for sensitive records. The support role should not share credentials, approve its own work, alter bank permissions, or release funds.',
 'A good procedure has a stop condition. Examples include missing authorization, a cross-entity balance, an unusual contract term, a conflicting source, a material unexplained variance, or an item that would change a reported conclusion. The stop condition should route to a person, not to a generic inbox. That keeps the offshore role productive while ensuring the business retains decisions that require context or authority.',
 'Test the workflow with ordinary and difficult examples. Include one complete item, one missing-document case, one timing difference, one duplicate-looking record, and one exception that needs an owner decision. Ask a second preparer to follow the written instructions without coaching. Compare selected evidence, status, escalation language, and final reviewer outcome. Repair the procedure before adding volume or widening permissions.',
 'Measure quality beside throughput. Useful signals include first-pass completion, ageing by owner, reopenings, missing-source frequency, unresolved decisions, and time waiting for client input. A high closure count can hide premature matching or silent deletions. Segment delays caused by evidence from delays caused by capacity so management can fix the right constraint rather than pressuring a preparer to guess.',
 'Revisit the workpaper when the accounting system, bank feed, payroll provider, entity structure, approval matrix, or close calendar changes. Add an effective date, preserve the prior version, and tell the reviewer what changed. A temporary workaround needs an owner and an expiry date. Otherwise a small exception becomes an invisible permanent process and the next person cannot tell which rule was intended.'
];
const conclusions = [
 'The practical standard is a reviewable trail: a complete population, source-linked analysis, explicit stop points, and an owner who can answer the remaining question. Offshore bookkeeping support works best when it increases preparation capacity without transferring protected authority by accident.',
 'Use this workflow as a role brief and a testable operating agreement. Start with a narrow lane, redacted examples, named review ownership, and a short feedback cycle. Expand only after the evidence shows that the process is repeatable and exceptions reach the right decision-maker.',
 'A clean handoff is not bureaucracy for its own sake. It is the mechanism that lets a distributed bookkeeping team move quickly while the business preserves context, approvals, and accountability. Keep those responsibilities visible in every queue, report, and workpaper.'
];
function words(text){ return text.trim().split(/\s+/).length; }
function article([slug,title,focus,problem,thesis], i){
 const sections = [
  ['Define the operating question', `For ${focus}, the first question is not how many records can be moved. It is what a responsible reviewer needs to know before the item can be accepted, held, or escalated. ${unique[(i+0)%unique.length]} ${problem[0].toUpperCase()+problem.slice(1)} creates a useful boundary because it names the operating problem without turning the support role into the final decision-maker.`],
  ['Describe the starting population', `${unique[(i+1)%unique.length]} For this workflow, define the population around ${problem}: identify the accounts, entity, period, source system, and expected count. Record exclusions such as pending imports or records awaiting an owner. If the population cannot be reproduced, the team cannot explain whether an apparent improvement came from resolution or from items quietly leaving the list.`],
  ['Build a source-linked workpaper', `${unique[(i+2)%unique.length]} A practical workpaper for ${focus} should include the original reference, relevant date, amount or quantity, source link, preparer note, status, reviewer, and next action. Keep proposed changes beside—not instead of—the source value. This structure lets a finance lead review the reasoning without repeating every search performed by the offshore bookkeeper.`],
  ['Separate preparation from approval', `${unique[(i+3)%unique.length]} The preparation lane may compare records, calculate a documented difference, request a missing document, or draft a proposed entry when policy explicitly permits it. It should stop before ${thesis}. Put the approval question in plain language and identify the person with authority. A role boundary that exists only in a verbal habit will fail when the team, system, or deadline changes.`],
  ['Route the hard cases', `${unique[(i+4)%unique.length]} For ${problem}, escalation should include the facts checked, the conflicting evidence, the decision required, the owner, and the deadline. Avoid “please review” as a complete handoff. Ask a bounded question such as whether the item should remain open, be connected to a named source, or be assessed under an existing policy. The reviewer can then answer without reconstructing the entire case.`],
  ['Use controls that fit remote work', `${unique[(i+5)%unique.length]} Remote bookkeeping requires practical access discipline. Give the support role only the tools and records needed for ${focus}; use named accounts and multifactor authentication; and make sensitive downloads traceable. Do not let a preparer approve their own exception or share credentials to overcome a deadline. Access removal and periodic review belong in the operating checklist, not in someone’s memory.`],
  ['Reconcile status to the ledger or source', `${unique[(i+6)%unique.length]} A queue is not evidence of completion until its states tie back to ${problem} and the relevant accounting record. At the cutoff, compare opened, resolved, deferred, and escalated items. Investigate records removed without disposition, changes lacking source support, and exceptions that reappear. This check distinguishes a controlled preparation process from a list that merely looks smaller.`],
  ['Measure quality and ageing', `${unique[(i+7)%unique.length]} Report volume with first-pass quality, age bands, reopenings, missing evidence, and time waiting for decisions. For ${focus}, segment delays caused by the client, the system, and processing capacity. That makes the next improvement specific: better source instructions, a clearer owner, a permission repair, or additional preparation capacity. Avoid a speed target that rewards unsupported closure.`],
  ['Pilot before widening scope', `${unique[(i+8)%unique.length]} Pilot ${focus} with representative cases: one ordinary item, one incomplete record, one timing difference, one duplicate-looking record, and one judgment-sensitive exception. Have another preparer follow the written steps. Review whether the same source was used, the same stop conditions were recognized, and the same owner received the question. Fix ambiguity before increasing volume.`],
  ['Maintain the procedure', `${unique[(i+9)%unique.length]} Revisit the instructions when ${problem} changes because of a new provider, entity, approval rule, system field, or close deadline. Add an effective date and retain the prior version. Ask the reviewer to confirm which fields, evidence, and escalation paths remain valid. This is how an offshore bookkeeping workflow stays dependable after its original author is no longer available.`],
  ['Practical conclusion', `${conclusions[i%conclusions.length]} For ${focus}, the durable result is a documented handoff that makes the next decision easier and keeps the business accountable for protected outcomes.`]
 ];
 const body = sections.map(([h,b])=>`## ${h}\n\n${b}`).join('\n\n');
 return `---\ntitle: "${title}"\ndescription: "A practical guide to ${focus} for Offshore Bookkeepers, with evidence, role boundaries, and reviewable handoffs."\npublished: "2026-08-21"\nupdated: "2026-08-21"\ncategory: "${focus[0].toUpperCase()+focus.slice(1)}"\ntype: "blog"\nfeaturedImage: "/thumbnails/${slug}.webp"\ntakeaways: ["Define the population and source trail.", "Keep preparation separate from approval.", "Measure ageing, rework, and unresolved decisions."]\nfaqs: [["What should an offshore bookkeeper own in this workflow?","The bookkeeper can prepare records, compare evidence, maintain the workpaper, and escalate exceptions under written instructions. An authorized finance reviewer keeps protected approvals and accounting judgments."],["How should a manager test the process?","Use representative complete and exception cases, then inspect source links, stop conditions, escalation quality, and reviewer decisions before expanding access or volume."]]\n---\nAugust 21, 2026 operating guide. This article discusses offshore bookkeeping preparation and review support. It is not accounting, tax, legal, payroll, or investment advice; client policy and authorized professionals control protected decisions.\n\n${body}\n`;
}
const dir = path.join(root,'content','blog');
for (const [i,t] of topics.entries()) fs.writeFileSync(path.join(dir,`${t[0]}.md`),article(t,i));
const manifest = topics.map(([slug])=>({route:`/blog/${slug}`,sourcePaths:[`content/blog/${slug}.md`],imagePath:`public/thumbnails/${slug}.webp`,promptReceipt:`.paperclip/daily-content/2026-08-21/prompts/${slug}.txt`}));
const md = path.join(root,'.paperclip','daily-content','2026-08-21'); fs.mkdirSync(path.join(md,'prompts'),{recursive:true});
fs.writeFileSync(path.join(md,'blog.json'),JSON.stringify(manifest,null,2)+'\n');
for (const [slug,title,,problem] of topics) fs.writeFileSync(path.join(md,'prompts',`${slug}.txt`),`Gemini hero prompt receipt\nArticle: ${title}\nSubject: editorial bookkeeping workspace showing ${problem}\nStyle: distinctive documentary business illustration, warm natural light, no text, no logos, no watermark, wide 1200x630 composition.\n`);
console.log(JSON.stringify({count:topics.length,words:topics.map(([s])=>[s,words(fs.readFileSync(path.join(dir,`${s}.md`),'utf8'))])}));
