import fs from 'node:fs';
import crypto from 'node:crypto';

const published = '2026-09-18';
const articles = [
  ['offshore-bookkeeping-saas-usage-based-billing-reconciliation','Reconcile usage-based SaaS billing before the invoice closes','SaaS bookkeeping','/thumbnails/bookkeeping-subscription-revenue-reconciliation.webp','/services/accounts-receivable-support','metered SaaS billing','usage export, contract rate card, customer entitlement, invoice draft, credit memo, and general ledger','A customer records 12.4 million API calls. The contract includes 10 million and prices the next tier at $0.0008 per call. The billing export shows 12.7 million because test traffic was included. The schedule preserves both populations, identifies the test workspace, and calculates the undisputed overage without editing the source export.','contract interpretation, excluded usage, pricing approval, revenue recognition, or issuance of a credit','billing owner and finance reviewer',[['FASB revenue recognition resources','https://www.fasb.org/page/PageContent?pageId=/projects/revenue-recognition-implementation.html'],['NIST log management guidance','https://csrc.nist.gov/pubs/sp/800/92/final']]],
  ['offshore-bookkeeping-restaurant-delivery-marketplace-promotion-reconciliation','Reconcile restaurant delivery promotions from order to payout','Restaurant bookkeeping','/thumbnails/ecommerce-bookkeeping-reconciliation-workflow.webp','/services/bank-reconciliation-support','delivery marketplace promotions','order detail, promotion funding report, commission statement, refund file, payout batch, and bank deposit','Orders total $8,400 before a $600 promotion. The restaurant funds $240, the marketplace funds $360, commissions are $1,680, and cash is $6,480. The reconciliation shows each component separately so the promotion is not mistaken for a processor fee or reduction of sales.','promotion ownership, tax presentation, revenue policy, disputed commissions, or customer refund approval','restaurant operator and finance reviewer',[['IRS restaurant tax center','https://www.irs.gov/businesses/small-businesses-self-employed/restaurants-tax-center'],['FTC advertising guidance','https://www.ftc.gov/business-guidance/advertising-marketing']]],
  ['offshore-bookkeeping-construction-equipment-rental-usage-check','Check construction equipment rental usage before approving the cost','Construction bookkeeping','/thumbnails/construction-job-costing-control-research.webp','/services/accounts-payable-processing','construction equipment rentals','rental agreement, dispatch ticket, job log, telematics or hour record, damage note, vendor invoice, and job-cost ledger','A lift is billed for 28 days on Project A, but dispatch records place it on Project B for six days and show an off-rent request three days before pickup. The workpaper separates contractual rental days, physical location, off-rent timing, and disputed days instead of allocating the full invoice by habit.','contract liability, damage responsibility, disputed days, capitalization, or final job allocation','project manager and accounts-payable approver',[['FAR equipment ownership and operating expense guidance','https://www.acquisition.gov/far/31.105'],['OSHA construction equipment resources','https://www.osha.gov/construction']]],
  ['offshore-bookkeeping-nonprofit-restricted-pledge-collection-rollforward','Roll restricted nonprofit pledges from promise through collection','Nonprofit bookkeeping','/thumbnails/nonprofit-fund-accounting-support-research.webp','/services/management-reporting-support','restricted pledge collections','signed pledge, donor restriction, campaign record, installment schedule, bank receipt, donor acknowledgment, and receivable ledger','A donor pledges $60,000 for a youth program in four quarterly installments. The second $15,000 receipt arrives with a memo naming a different initiative. The rollforward matches the cash but leaves the restriction conflict open for the development and finance owners rather than silently changing the fund code.','whether a promise is recognized, how a restriction applies, collectibility, modification, or release from restriction','development director and nonprofit finance owner',[['FASB not-for-profit accounting resources','https://www.fasb.org/not-for-profit-advisory-committee'],['IRS charitable organizations resources','https://www.irs.gov/charities-non-profits/charitable-organizations']]],
  ['offshore-bookkeeping-law-firm-settlement-disbursement-ledger','Build a law-firm settlement disbursement ledger with reviewable evidence','Law firm bookkeeping','/thumbnails/law-firm-trust-account-bookkeeping-boundaries.webp','/services/law-firm-bookkeeping','settlement disbursements','settlement statement, trust receipt, matter ledger, lien correspondence, client authorization, payment proof, and operating transfer','A $125,000 settlement enters trust. The draft statement lists $40,000 of fees, $3,200 of case costs, a $9,500 medical lien, and $72,300 due to the client. A later lien letter requests $10,250. The ledger holds the disputed $750 and prevents the client amount from being treated as final before attorney review.','legal entitlement, lien resolution, fee approval, trust transfer, or release of client funds','responsible attorney or trust-account supervisor',[['ABA Model Rule 1.15','https://www.americanbar.org/groups/professional_responsibility/publications/model_rules_of_professional_conduct/rule_1_15_safekeeping_property/'],['ABA client protection resources','https://www.americanbar.org/groups/professional_responsibility/resources/client-protection/']]],
  ['offshore-bookkeeping-property-utility-rubs-reconciliation','Reconcile tenant utility allocations before posting RUBS charges','Property bookkeeping','/thumbnails/property-bookkeeping-rent-roll-controls.webp','/services/property-bookkeeping','ratio utility billing charges','utility invoice, meter period, occupied-unit roster, lease terms, allocation inputs, tenant charges, credits, and property ledger','A 40-unit property receives a $7,800 water bill. Three units were vacant, two tenants moved midmonth, and one lease excludes shared irrigation. The schedule documents the eligible pool and days in occupancy, then compares calculated charges with the upload file without deciding whether a lease permits the method.','lease interpretation, allocation method, consumer notice, local compliance, or approval of tenant credits','property manager and authorized compliance reviewer',[['HUD multifamily housing resources','https://www.hud.gov/hud-partners/multifamily'],['EPA WaterSense resources','https://www.epa.gov/watersense']]],
  ['offshore-bookkeeping-manufacturing-tolling-inventory-reconciliation','Reconcile toll-manufacturing inventory across owner and processor records','Manufacturing bookkeeping','/thumbnails/bookkeeping-inventory-count-handoff.webp','/services/month-end-close-support','toll-manufacturing inventory','owner shipment, processor receipt, bill of materials, production report, scrap log, return shipment, processor invoice, and inventory ledger','An owner ships 10,000 kilograms of resin. The processor reports 9,300 kilograms in finished goods, 420 in work in process, 180 as normal scrap, and 60 unexplained. The bridge accounts for 9,960 kilograms and escalates the remaining 40 instead of forcing it into scrap.','ownership, normal-yield policy, loss responsibility, inventory valuation, or acceptance of processor variance','operations owner and controller',[['FASB inventory project resources','https://www.fasb.org/page/PageContent?pageId=/projects/inventory.html'],['NIST manufacturing resources','https://www.nist.gov/mep']]],
  ['offshore-bookkeeping-healthcare-era-takeback-reconciliation','Reconcile healthcare ERA takebacks without rewriting prior receipts','Healthcare bookkeeping','/thumbnails/clinic-bookkeeping-reconciliation-research.webp','/services/bank-reconciliation-support','electronic remittance takebacks','ERA file, claim reference, original remittance, payer correspondence, refund request, later offset, bank deposit, and receivable ledger','A payer originally allows $2,400 and later withholds $600 from an unrelated $8,000 remittance. The deposit is $7,400. The schedule links the takeback to the original claim, preserves the new batch at gross value, and keeps appeal status visible without exposing unnecessary patient information.','medical necessity, appeal strategy, refund authorization, contractual allowance, or final revenue treatment','revenue-cycle owner and finance reviewer',[['CMS electronic billing and EDI transactions','https://www.cms.gov/medicare/coding-billing/electronic-billing'],['HHS minimum necessary guidance','https://www.hhs.gov/hipaa/for-professionals/privacy/guidance/minimum-necessary-requirement/index.html']]],
  ['offshore-bookkeeping-agency-media-prepayment-reconciliation','Reconcile agency media prepayments to campaigns, delivery, and client billing','Agency bookkeeping','/thumbnails/offshore-bookkeeping-project-margin-bridge.webp','/services/accounts-payable-processing','agency media prepayments','client authorization, media plan, insertion order, vendor invoice, proof of delivery, platform spend, client invoice, and ledger','An agency prepays $50,000 for a campaign. Platform delivery is $38,000 at month-end, $4,000 is canceled, and $8,000 remains available for next month. The schedule separates delivered spend, refundable credit, and future placement while checking which amount may be billed under the client agreement.','principal-versus-agent presentation, billable amount, cancellation ownership, revenue timing, or write-off','account lead and finance approver',[['FTC digital advertising guidance','https://www.ftc.gov/business-guidance/advertising-marketing/online-advertising-marketing'],['FASB revenue recognition resources','https://www.fasb.org/page/PageContent?pageId=/projects/revenue-recognition-implementation.html']]],
  ['offshore-bookkeeping-mobile-app-store-payout-reconciliation','Reconcile mobile app-store payouts to subscriptions, fees, tax, and refunds','SaaS bookkeeping','/thumbnails/bookkeeping-subscription-revenue-reconciliation.webp','/services/ecommerce-bookkeeping','mobile app-store payouts','store financial report, subscription event export, fee schedule, tax report, refund file, currency conversion, payout, and ledger','A store reports $24,000 of customer billings, $3,600 of platform commission, $1,900 of taxes withheld, $500 of refunds, and a $18,000 payout. The reconciliation proves the arithmetic and separates transaction currency from payout currency rather than booking the deposit as subscription revenue.','tax responsibility, gross-versus-net presentation, revenue recognition, refund approval, or foreign-exchange policy','product finance owner and controller',[['Apple developer financial reports help','https://developer.apple.com/help/app-store-connect/view-and-download-financial-reports/overview-of-financial-reports/'],['Google Play financial reports documentation','https://support.google.com/googleplay/android-developer/answer/6135870']]],
  ['offshore-bookkeeping-logistics-fuel-surcharge-reconciliation','Reconcile logistics fuel surcharges to shipments and contract indexes','Logistics bookkeeping','/thumbnails/offshore-bookkeeping-project-cost-source-map.webp','/services/accounts-receivable-support','logistics fuel surcharges','shipment record, lane and mileage, contract base fuel price, published index, surcharge table, invoice, credit memo, and receivable ledger','A carrier bills 18 loads using a 24% surcharge. The weekly index supports 22% for 11 loads and 24% for seven loads because dispatch dates cross the reset. The schedule recalculates each population and isolates the difference without changing the customer invoice before approval.','which index date applies, contract exceptions, taxable base, customer dispute, or credit issuance','transportation manager and finance approver',[['U.S. EIA diesel fuel data','https://www.eia.gov/petroleum/gasdiesel/'],['FMCSA financial responsibility guidance','https://www.fmcsa.dot.gov/registration/insurance-filing-requirements']]],
  ['offshore-bookkeeping-franchise-system-sales-royalty-tieout','Tie franchise system sales to royalty invoices and cash','Franchise bookkeeping','/thumbnails/offshore-bookkeeping-franchise-royalty-reconciliation.png','/services/management-reporting-support','franchise royalty reporting','point-of-sale sales, excluded-sales detail, franchise agreement rate, royalty report, marketing-fund charge, invoice, payment, and general ledger','A franchise location reports $210,000 of gross sales, $8,000 of permitted exclusions, a 6% royalty, and a 2% marketing charge. The invoice uses $205,000 as its base. The tieout documents both bases, calculates the $3,000 difference, and asks which exclusions are contractually supported.','contract interpretation, audit rights, disputed exclusions, tax treatment, or enforcement action','franchise operations owner and finance reviewer',[['FTC Franchise Rule compliance guide','https://www.ftc.gov/business-guidance/resources/franchise-rule-compliance-guide'],['SBA franchise business guidance','https://www.sba.gov/business-guide/plan-your-business/buy-existing-business-or-franchise']]]
];

const shared = (a) => `The objective is a reviewable explanation, not a forced zero. Define the entity, period, cutoff, currency, systems, accounts, and locations before exporting data. Save untouched, read-only source files with extraction timestamps, filters, row counts, and control totals. A report that can change later needs a version reference. A missing record remains an exception; it is never permission to estimate a convenient amount.

Start from the last reviewed balance. Show additions, applications, reversals, transfers, refunds, corrections, and closing balance on separate lines. Compare the schedule independently with each relevant subledger, general ledger account, provider statement, and bank movement. Net cash can agree while the receivable, liability, expense, revenue, customer, or vendor detail is wrong.

Use one row for each traceable event. Include stable identifiers, effective date, service period, gross amount, deductions, fees, taxes, reserves, refunds, currency, evidence link, status, owner, and due date. Do not combine unrelated items because they share a deposit date. Keep original and corrected values in separate fields, and make formulas visible to the reviewer.

Use precise statuses: ready to match, matched, timing item, missing evidence, amount mismatch, duplicate risk, policy question, awaiting approval, disputed, and closed with evidence. “Checking” is not a status unless it identifies the question, owner, and next date. Carry unresolved items forward with their original age and reference.

Protect access as carefully as the arithmetic. Use named accounts, multifactor authentication, and read-only or limited permissions where possible. Separate preparation from payment release, bank-detail changes, credits, write-offs, journal posting, period locking, and deletion. Store sensitive evidence only in approved systems, and use masked identifiers when a full name or account number is unnecessary.

Test completeness in both directions. Select records from source exports and trace them into the workpaper; then select workpaper lines and trace them back to original evidence. Reperform large, unusual, manual, old, zero-value, and post-cutoff items. Equal and opposite entries deserve attention because they can hide duplicates or misdirection.

The reviewer should confirm the population, control totals, formulas, exception ownership, proposed entries, and decisions. Review notes need a question, owner, date, response, and closure evidence. Preserve the first answer when it changes so the file explains how the final treatment was reached.

Close with untouched exports, the reconciliation, evidence index, exception log, approved entries, reviewer decisions, and a one-page summary. State what tied, what remains open, the value exposed, the next owner, and the next review date. Link the package from the close checklist using a consistent entity-process-period-version name.`;

function render(a) { const [slug,title,category,image,service,subject,evidence,example,decision,reviewer,sources]=a; return `---
title: "${title}"
description: "A practical offshore bookkeeping workflow for ${subject}, with source evidence, exception ownership, and clear review boundaries."
published: "${published}"
category: "${category}"
type: "blog"
featuredImage: "${image}"
sources: ${JSON.stringify(sources.map(([name,url])=>({name,url})))}
takeaways: ["Define and reconcile the complete source population before investigating differences.","Give each exception evidence, an owner, a due date, and a focused decision request.","Keep approvals and accounting judgment with the authorized company reviewer."]
faqs: [["Can an offshore bookkeeper prepare this reconciliation?","Yes. A bookkeeper can gather authorized records, perform documented comparisons, maintain the exception queue, and prepare a review-ready handoff."],["What stays with the company reviewer?","Contract interpretation, accounting policy, approvals, legal conclusions, write-offs, and other judgment calls remain with the authorized owner or professional adviser."]]
---
Published September 18, 2026. This guide covers bookkeeping preparation and review support. It is not accounting, tax, legal, payroll, medical, or regulatory advice.

## Why ${subject} needs a separate workpaper

The records for ${subject} rarely arrive in one place or at one time. A reliable packet connects the ${evidence}. Posting the final bank amount alone removes the evidence needed to explain timing, fees, adjustments, ownership, and unresolved differences.

Authoritative background includes [${sources[0][0]}](${sources[0][1]}) and [${sources[1][0]}](${sources[1][1]}). These sources inform the workflow but do not replace the company’s contract, accounting policy, jurisdiction-specific rules, or professional advice. Record the source version and access date when a changing rule affects the procedure.

## Define the population and control totals

${shared(a).split('\n\n').slice(0,3).join('\n\n')}

## Work through a concrete example

${example}

This example is useful because a plausible net result can conceal incorrect components. First reproduce the source arithmetic. Then compare it with the approved contract or procedure. Finally show the ledger effect. Write exceptions as observed facts: one source reports a value, another reports a different value, and the difference is quantified. Possible causes belong in a separate note until evidence confirms them.

Set escalation thresholds under company policy, but do not use dollars as the only trigger. A small repeated error, approaching dispute deadline, access concern, altered payment detail, or missing approval may need immediate attention. Aging matters too: a modest item open for four months can reveal a broken handoff.

## Keep preparation separate from judgment

An offshore bookkeeper can download approved reports, compare identifiers and amounts, reperform arithmetic, request missing documents, update statuses, and draft an entry for review. The bookkeeper stops when the work requires ${decision}. That belongs to the ${reviewer}.

Make the decision request answerable without rebuilding the file. Include the amount, affected period, deadline, source links, observed difference, available options, and operational consequence of delay. Store the response with the workpaper rather than relying on a private chat.

${shared(a).split('\n\n').slice(3,5).join('\n\n')}

## Review in both directions

${shared(a).split('\n\n').slice(5,7).join('\n\n')}

Track population count, matched and unmatched values, oldest exception, corrections returned, and percentage reviewed by deadline. These are workflow signals, not promises of financial performance. Repeated exceptions should lead to a better intake form, export, naming convention, or approval path.

## Close without hiding open items

${shared(a).split('\n\n').slice(7).join('\n\n')}

For help defining the preparation lane, see [the relevant Offshore Bookkeepers service](${service}). If your company needs a Philippines-based bookkeeper to maintain the schedule and route exceptions while your finance owner retains approval, [plan the role with Offshore Bookkeepers](/contact-us).
`; }

const manifest=[];
for (const a of articles) { const sourcePath=`content/blog/${a[0]}.md`; const body=render(a); fs.writeFileSync(sourcePath,body); manifest.push({family:a[2],topic:a[1],title:a[1],slug:a[0],route:`/blog/${a[0]}`,canonical:`https://offshorebookkeepers.com/blog/${a[0]}`,sourcePath,featuredImage:a[3],sources:a[10].map(([name,url])=>({name,url})),publicationDate:published,status:'prepared',contentHash:crypto.createHash('sha256').update(body).digest('hex'),wordCount:(body.match(/\b[\w’'-]+\b/g)||[]).length}); }
fs.mkdirSync(`.paperclip/daily-content/${published}`,{recursive:true});
fs.writeFileSync(`.paperclip/daily-content/${published}/blog-off-68.json`,JSON.stringify(manifest,null,2)+'\n');
console.log(`Created ${manifest.length} OFF-68 articles.`);
