import fs from 'node:fs';
import crypto from 'node:crypto';

const published = '2026-09-23';
let articles = [
  ['offshore-bookkeeping-veterinary-wellness-plan-reconciliation','Reconcile veterinary wellness-plan collections, services, and deferred balances','Veterinary bookkeeping','/thumbnails/clinic-bookkeeping-reconciliation-research.webp','/services/healthcare-bookkeeping','veterinary wellness-plan activity','practice-management plan roster, payment processor settlement, service history, cancellation report, refund log, and general ledger','A clinic collects $12,600 from active plans during the month. The service report shows $9,100 of plan-covered care, while $700 of failed payments and a $300 cancellation refund appear in separate reports. The bridge keeps cash, delivered services, failed collections, and refund activity separate so the reviewer can apply the clinic’s approved revenue policy.','revenue recognition, plan eligibility, cancellation terms, clinical coding, refund approval, or write-off','practice manager and finance reviewer',[['IRS recordkeeping guidance','https://www.irs.gov/businesses/small-businesses-self-employed/recordkeeping'],['AVMA practice management resources','https://www.avma.org/resources-tools/veterinary-economics/practice-management']]],
  ['offshore-bookkeeping-solar-installer-progress-billing-reconciliation','Reconcile solar installation progress billings to milestones and project costs','Construction bookkeeping','/thumbnails/construction-job-costing-control-research.webp','/services/construction-bookkeeping','solar installation progress billing','signed contract, approved change order, permit status, milestone certificate, customer invoice, payment receipt, subcontractor cost, and project ledger','A project has a $120,000 contract with billings of 10% at signing, 50% after equipment delivery, and 40% after permission to operate. The billing system shows $72,000 invoiced, but the delivery packet supports only $54,000 of qualifying equipment after a substitution. The schedule isolates the unsupported milestone amount for review.','milestone achievement, contract interpretation, revenue recognition, change-order approval, lien compliance, or customer dispute','project manager and controller',[['U.S. Department of Energy solar project resources','https://www.energy.gov/eere/solar/solar-energy-resources-consumers'],['FASB revenue recognition resources','https://www.fasb.org/page/PageContent?pageId=/projects/revenue-recognition-implementation.html']]],
  ['offshore-bookkeeping-home-health-evv-payroll-billing-bridge','Build a home-health EVV-to-payroll-and-billing reconciliation','Healthcare bookkeeping','/thumbnails/clinic-bookkeeping-reconciliation-research.webp','/services/payroll-processing-support','home-health visit records','authorized care schedule, electronic visit verification export, approved timesheet, payroll register, payer claim batch, remittance, and general ledger','EVV records show 1,240 visit hours. Approved payroll includes 1,218 hours, while the billing batch includes 1,205. The bridge identifies 22 hours awaiting supervisor approval and 13 approved hours excluded from claims, without assuming that every recorded minute is payable or billable.','care authorization, clinical compliance, wage entitlement, claim eligibility, coding, privacy access, or final adjustment','clinical operations owner, payroll approver, and revenue-cycle lead',[['CMS electronic visit verification','https://www.medicaid.gov/medicaid/home-community-based-services/guidance/electronic-visit-verification-evv'],['U.S. Department of Labor recordkeeping','https://www.dol.gov/agencies/whd/fact-sheets/21-flsa-recordkeeping']]],
  ['offshore-bookkeeping-insurance-agency-commission-clawback-reconciliation','Reconcile insurance-agency commissions and carrier clawbacks','Insurance agency bookkeeping','/thumbnails/bookkeeping-commission-accrual-review.webp','/services/accounts-receivable-support','insurance carrier commission activity','carrier statement, policy roster, commission schedule, new-business report, cancellation report, clawback detail, cash receipt, and commission ledger','A carrier statement shows $31,000 of new commissions and $4,800 of reversals. The cancellation report supports $3,900 of reversals; the remaining $900 refers to policy identifiers absent from the agency roster. The schedule ties the supported net cash and leaves the unmatched clawback open.','policy status, producer entitlement, carrier contract interpretation, revenue recognition, dispute filing, or write-off','agency principal and finance reviewer',[['NAIC insurance industry resources','https://content.naic.org/consumer'],['IRS recordkeeping guidance','https://www.irs.gov/businesses/small-businesses-self-employed/recordkeeping']]],
  ['offshore-bookkeeping-ecommerce-buy-now-pay-later-settlement','Reconcile buy-now-pay-later settlements to ecommerce orders','Ecommerce bookkeeping','/thumbnails/ecommerce-bookkeeping-reconciliation-workflow.webp','/services/ecommerce-bookkeeping','buy-now-pay-later settlements','store order export, provider transaction report, fee schedule, refund report, dispute file, settlement statement, bank deposit, and general ledger','The store records $48,000 of qualifying orders. The provider settles $44,620 after $1,440 of fees, $1,600 of refunds, and a $340 dispute hold. A separate $500 refund was funded from a later settlement. The bridge preserves the settlement timing instead of forcing every deduction into the order week.','consumer-credit compliance, fee classification, refund authorization, dispute response, revenue presentation, or write-off','ecommerce operations owner and controller',[['Consumer Financial Protection Bureau BNPL resources','https://www.consumerfinance.gov/consumer-tools/buy-now-pay-later-loans/'],['FTC online business guidance','https://www.ftc.gov/business-guidance']]],
  ['offshore-bookkeeping-nonprofit-reimbursement-grant-receivable','Reconcile nonprofit reimbursement grants from eligible cost to cash','Nonprofit bookkeeping','/thumbnails/nonprofit-fund-accounting-support-research.webp','/services/nonprofit-bookkeeping','reimbursement-grant receivables','award agreement, approved budget, expense detail, payroll allocation, reimbursement request, funder response, cash receipt, and restricted-fund ledger','A nonprofit submits $85,000 of costs under a reimbursement award. The funder approves $79,500, holds $3,000 pending support, and rejects $2,500 outside the grant period. The schedule maintains each population separately and ties the approved receivable to later cash without silently reallocating rejected costs.','cost eligibility, allocation methodology, donor restrictions, revenue recognition, appeal, or reclassification','program owner and nonprofit controller',[['Uniform Guidance cost principles','https://www.ecfr.gov/current/title-2/subtitle-A/chapter-II/part-200'],['FASB not-for-profit resources','https://www.fasb.org/page/PageContent?pageId=/standards/implementation-and-practical-guidance/not-for-profit-entities.html']]],
  ['offshore-bookkeeping-property-cam-reconciliation','Prepare a commercial-property CAM reconciliation by tenant','Property bookkeeping','/thumbnails/property-bookkeeping-rent-roll-controls.webp','/services/property-bookkeeping','common-area maintenance reconciliation','tenant lease abstract, property budget, vendor invoices, allocation workbook, occupancy schedule, monthly billings, tenant credits, and property ledger','Recoverable property costs total $360,000. The occupancy schedule allocates 12% to one tenant, but the lease cap limits the current-year increase and excludes a capital repair. The schedule shows the raw share, exclusion, cap adjustment, amounts already billed, and proposed settlement separately.','lease interpretation, recoverability, allocation rules, capital classification, tenant notice, or final settlement approval','property manager and authorized lease reviewer',[['FASB leases implementation resources','https://www.fasb.org/page/PageContent?pageId=/projects/leases-implementation.html'],['EPA commercial buildings resources','https://www.energystar.gov/buildings']]],
  ['offshore-bookkeeping-orthodontic-treatment-plan-deposit-rollforward','Roll forward orthodontic treatment-plan deposits and monthly charges','Dental bookkeeping','/thumbnails/clinic-bookkeeping-reconciliation-research.webp','/services/healthcare-bookkeeping','orthodontic treatment-plan deposits','treatment contract, patient ledger, deposit receipt, scheduled charge report, insurance estimate, refund log, bank deposit, and general ledger','A treatment plan totals $6,000 with a $1,200 deposit and 24 scheduled monthly charges. The patient ledger applies $1,450 in the first month, while the approved schedule supports $1,200 and a separate $150 records fee. The rollforward isolates the extra $100 and keeps the insurance estimate outside collected cash.','treatment completion, contract interpretation, refund responsibility, revenue policy, privacy access, or bad-debt treatment','practice manager and finance reviewer',[['HHS minimum necessary guidance','https://www.hhs.gov/hipaa/for-professionals/privacy/guidance/minimum-necessary-requirement/index.html'],['Consumer Financial Protection Bureau medical debt resources','https://www.consumerfinance.gov/consumer-tools/medical-debt/']]],
  ['offshore-bookkeeping-franchise-marketing-fund-reconciliation','Reconcile franchise marketing-fund collections and approved spending','Franchise bookkeeping','/thumbnails/offshore-bookkeeping-franchise-royalty-reconciliation.png','/services/management-reporting-support','franchise marketing-fund activity','franchise agreement schedule, system-sales report, fund assessment invoices, cash receipts, approved campaign budget, vendor invoices, credits, and fund ledger','The network assesses $96,000 for the quarter. Cash receipts are $92,000, approved campaign invoices are $70,000, and a $6,000 vendor credit remains unapplied. The rollforward separates receivables, available cash, committed spend, and the credit instead of treating the bank balance as the fund position.','agreement interpretation, permitted fund use, allocation, campaign approval, disclosure obligations, or write-off','franchise executive and fund finance reviewer',[['FTC Franchise Rule compliance guide','https://www.ftc.gov/business-guidance/resources/franchise-rule-compliance-guide'],['SBA franchise business guidance','https://www.sba.gov/business-guide/plan-your-business/buy-existing-business-or-franchise']]],
  ['offshore-bookkeeping-logistics-detention-charge-reconciliation','Reconcile logistics detention charges from timestamps to collection','Logistics bookkeeping','/thumbnails/offshore-bookkeeping-project-cost-source-map.webp','/services/accounts-receivable-support','detention-charge billing','rate confirmation, appointment record, geofence timestamps, driver record, bill of lading, free-time rule, customer invoice, dispute log, and receivable ledger','A load spends 210 minutes at a facility with 120 free minutes and a $75 hourly detention rate billed in 30-minute increments. One timestamp conflicts with the signed departure record by 20 minutes. The schedule calculates both outcomes and routes the timestamp decision before invoicing.','contract terms, timestamp precedence, force majeure, customer dispute, billing approval, or credit issuance','transportation operations owner and finance approver',[['FMCSA hours-of-service resources','https://www.fmcsa.dot.gov/regulations/hours-service'],['U.S. Department of Transportation freight resources','https://ops.fhwa.dot.gov/freight/']]],
  ['offshore-bookkeeping-staffing-timesheet-payroll-billing-reconciliation','Reconcile staffing timesheets to payroll and client billing','Staffing bookkeeping','/thumbnails/payroll-journal-preparation-controls.webp','/services/payroll-processing-support','staffing timesheet activity','worker assignment, approved timesheet, pay-rate table, bill-rate table, payroll register, client invoice, adjustment log, and general ledger','Approved timesheets contain 3,480 regular hours and 210 overtime hours. Payroll includes all approved hours, but client invoices omit 36 hours from late-approved shifts and apply an outdated bill rate to 24 hours. The bridge quantifies both exceptions without changing pay already approved.','worker classification, wage entitlement, overtime rules, client contract interpretation, invoice approval, or credit issuance','staffing operations owner, payroll approver, and billing manager',[['U.S. Department of Labor hours-worked guidance','https://www.dol.gov/agencies/whd/fact-sheets/22-flsa-hours-worked'],['U.S. Department of Labor recordkeeping','https://www.dol.gov/agencies/whd/fact-sheets/21-flsa-recordkeeping']]],
  ['offshore-bookkeeping-manufacturing-warranty-vendor-recovery','Reconcile manufacturing warranty costs and vendor recoveries','Manufacturing bookkeeping','/thumbnails/manufacturing-cost-accounting-research.webp','/services/month-end-close-support','warranty vendor-recovery activity','warranty claim, serial or batch reference, service work order, parts issue, labor record, supplier agreement, debit memo, cash recovery, and warranty ledger','Warranty work orders total $44,000 of parts and labor. Supplier agreements support $18,000 of recoveries, debit memos issued total $15,500, and $11,000 has been collected. The schedule keeps incurred cost, eligible recovery, submitted claim, and cash as separate stages.','warranty coverage, product defect conclusion, recovery eligibility, reserve methodology, claim approval, or write-off','quality owner and manufacturing controller',[['NIST manufacturing resources','https://www.nist.gov/mep'],['CPSC business guidance','https://www.cpsc.gov/Business--Manufacturing/Business-Education']]],
];

// Reuse repository-native media while preserving the article-specific subjects.
articles.find((a) => a[0] === 'offshore-bookkeeping-insurance-agency-commission-clawback-reconciliation')[3] = '/thumbnails/bookkeeping-commission-accrual-workflow.webp';
articles.find((a) => a[0] === 'offshore-bookkeeping-manufacturing-warranty-vendor-recovery')[3] = '/thumbnails/bookkeeping-quality-scorecard.webp';

articles = [
  ['offshore-bookkeeping-commercial-cleaning-job-profitability','Reconcile commercial-cleaning job profitability from shifts to invoices','Commercial cleaning bookkeeping','/thumbnails/offshore-bookkeeping-project-margin-bridge.webp','/services/management-reporting-support','commercial-cleaning job profitability','signed scope, site roster, approved shifts, payroll detail, supply issues, subcontractor bills, customer invoices, credits, and job-cost ledger','A monthly contract bills $28,000. Approved labor is $13,400, supplies are $2,300, and subcontractors are $4,100. A missed weekend shift produced a $900 customer credit, while payroll includes $620 coded to the wrong site. The bridge shows reported margin before and after each supported correction.','service-quality conclusions, wage entitlement, contract interpretation, credit approval, cost allocation policy, or margin targets','operations manager and controller',[['U.S. Department of Labor recordkeeping','https://www.dol.gov/agencies/whd/fact-sheets/21-flsa-recordkeeping'],['OSHA cleaning industry resources','https://www.osha.gov/cleaning-industry']]],
  ['offshore-bookkeeping-saas-annual-contract-billing-rollforward','Roll forward SaaS annual contracts from billing to deferred revenue','SaaS bookkeeping','/thumbnails/bookkeeping-unbilled-revenue-review.svg','/services/month-end-close-support','SaaS annual-contract billing','executed order form, subscription roster, invoice, payment record, service dates, credit memo, cancellation log, deferred-revenue schedule, and general ledger','A customer prepays $24,000 for twelve months beginning July 15. The billing system starts service on July 1, while the signed order and provisioning record support July 15. The rollforward preserves both dates and quantifies the disputed half-month rather than selecting a revenue start date.','contract enforceability, performance obligations, revenue-recognition policy, cancellation rights, credit approval, or accounting conclusions','revenue operations owner and controller',[['FASB revenue recognition resources','https://www.fasb.org/page/PageContent?pageId=/projects/revenue-recognition-implementation.html'],['FTC business guidance','https://www.ftc.gov/business-guidance']]],
  ['offshore-bookkeeping-hoa-special-assessment-rollforward','Reconcile HOA special assessments from owner billing to project spending','HOA bookkeeping','/thumbnails/bookkeeping-customer-deposit-reconciliation.webp','/services/property-bookkeeping','HOA special-assessment activity','board resolution, owner roster, assessment schedule, invoices, receipts, waivers, project contracts, vendor bills, restricted cash, and assessment ledger','The association approves a $240,000 assessment. Owner billings total $238,000 because two units were omitted, receipts are $196,000, and approved project invoices are $121,000. The schedule keeps authorization, billing completeness, collections, restricted cash, and spending separate.','governing-document interpretation, owner liability, waiver approval, fund restrictions, collections action, or project authorization','community manager, board treasurer, and accounting reviewer',[['HUD condominium resources','https://www.hud.gov/housing-counseling'],['IRS recordkeeping guidance','https://www.irs.gov/businesses/small-businesses-self-employed/recordkeeping']]],
  ['offshore-bookkeeping-event-venue-deposit-rollforward','Roll forward event-venue deposits, final bills, refunds, and credits','Hospitality bookkeeping','/thumbnails/bookkeeping-customer-deposit-reconciliation.webp','/services/accounts-receivable-support','event-venue deposits','signed event order, deposit invoice, processor settlement, change order, final consumption report, final invoice, refund log, credits, and customer ledger','A client pays a $15,000 deposit for a $42,000 event estimate. Approved changes add $3,600, final consumption reduces the beverage charge by $1,100, and a $750 damage hold remains unresolved. The rollforward shows each component without treating the initial estimate as the final receivable.','contract terms, cancellation rights, damage responsibility, gratuity treatment, refund approval, or revenue recognition','event manager and finance reviewer',[['FTC business guidance','https://www.ftc.gov/business-guidance'],['IRS recordkeeping guidance','https://www.irs.gov/businesses/small-businesses-self-employed/recordkeeping']]],
  ['offshore-bookkeeping-freight-invoice-accessorial-audit','Audit freight invoices for rates, accessorials, credits, and duplicates','Logistics bookkeeping','/thumbnails/bookkeeping-credit-memo-control-research.webp','/services/month-end-close-support','freight invoice audit activity','rate confirmation, tender, bill of lading, delivery record, carrier invoice, accessorial evidence, duplicate report, credit memo, payment batch, and freight ledger','A carrier bills $18,400 across 26 loads. Base rates reproduce to $16,900, supported accessorials total $900, and two detention charges totaling $600 lack timestamp evidence. A repeated invoice number creates a further $740 duplicate risk. The audit queues both issues before payment.','rate-contract interpretation, service acceptance, detention entitlement, carrier dispute, credit approval, or payment release','logistics manager and accounts-payable approver',[['FMCSA registration and safety resources','https://www.fmcsa.dot.gov/registration'],['U.S. DOT freight resources','https://ops.fhwa.dot.gov/freight/']]],
  ['offshore-bookkeeping-legal-settlement-cost-ledger','Maintain a matter-level legal settlement and case-cost ledger','Legal services bookkeeping','/thumbnails/offshore-bookkeeping-project-margin-bridge.webp','/services/legal-bookkeeping','matter-level settlement and case-cost activity','matter roster, engagement terms, court record, settlement statement, client-cost ledger, trust transfer evidence, vendor bills, disbursement approvals, and general ledger','A matter receives $180,000. The approved statement identifies $54,000 of fees, $12,800 of reimbursable case costs, and $113,200 due to the client. The cost ledger contains another $1,450 vendor invoice not listed on the statement, so the packet flags it instead of changing the distribution.','legal entitlement, settlement terms, trust-account release, fee approval, client authorization, privilege, or professional-responsibility conclusions','responsible attorney and authorized accounting reviewer',[['American Bar Association Model Rules','https://www.americanbar.org/groups/professional_responsibility/publications/model_rules_of_professional_conduct/'],['IRS recordkeeping guidance','https://www.irs.gov/businesses/small-businesses-self-employed/recordkeeping']]],
  ['offshore-bookkeeping-subscription-usage-overage-billing','Reconcile subscription usage records to overage invoices','Subscription business bookkeeping','/thumbnails/bookkeeping-unbilled-revenue-review.svg','/services/accounts-receivable-support','subscription usage and overage billing','customer contract, plan roster, metering export, data-correction log, rate table, invoice batch, credits, payment record, and receivable ledger','A customer plan includes 100,000 units and records 128,400 units. The billing engine invoices 31,200 overage units because a late correction was not loaded. The bridge isolates 2,800 disputed units and shows the invoice effect at the contracted tier rate.','meter validity, contract interpretation, service acceptance, rate approval, credit authorization, or revenue recognition','product operations owner and billing approver',[['NIST data integrity glossary','https://csrc.nist.gov/glossary/term/data_integrity'],['FASB revenue recognition resources','https://www.fasb.org/page/PageContent?pageId=/projects/revenue-recognition-implementation.html']]],
  ['offshore-bookkeeping-fitness-membership-freeze-reconciliation','Reconcile fitness memberships, freezes, cancellations, and collections','Fitness business bookkeeping','/thumbnails/recurring-charge-register.svg','/services/accounts-receivable-support','fitness membership billing','membership agreement, active-member roster, freeze request, cancellation log, recurring billing file, processor settlement, refunds, chargebacks, and membership ledger','The roster lists 820 active memberships. Billing includes 798 accounts, 14 approved freezes, six cancellations awaiting cutoff review, and two failed charges. A separate refund batch contains three amounts not linked to member identifiers. The schedule preserves each status and exception.','consumer-contract interpretation, cancellation effectiveness, refund rights, chargeback response, pricing approval, or revenue policy','membership operations manager and finance reviewer',[['FTC consumer protection resources','https://www.ftc.gov/news-events/topics/truth-advertising'],['IRS recordkeeping guidance','https://www.irs.gov/businesses/small-businesses-self-employed/recordkeeping']]],
  ['offshore-bookkeeping-equipment-rental-damage-deposit-rollforward','Roll forward equipment-rental deposits, extensions, damage charges, and refunds','Equipment rental bookkeeping','/thumbnails/bookkeeping-customer-deposit-reconciliation.webp','/services/accounts-receivable-support','equipment-rental deposits','rental contract, asset checkout, deposit receipt, extension approval, return inspection, damage evidence, final invoice, refund batch, and rental ledger','A customer pays a $4,000 deposit against a $9,500 rental. A three-day extension adds $1,200 and the return report notes $850 of possible damage, but the repair estimate is not approved. The rollforward bills the supported extension and keeps the damage hold pending review.','damage responsibility, contract enforcement, repair approval, deposit offset, refund timing, or revenue recognition','rental operations owner and finance approver',[['FTC business guidance','https://www.ftc.gov/business-guidance'],['IRS recordkeeping guidance','https://www.irs.gov/businesses/small-businesses-self-employed/recordkeeping']]],
  ['offshore-bookkeeping-food-manufacturer-slotting-deduction-reconciliation','Reconcile retailer slotting fees, deductions, and promotional allowances','Food manufacturing bookkeeping','/thumbnails/bookkeeping-quality-scorecard.webp','/services/month-end-close-support','retailer deductions and promotional allowances','customer agreement, price list, promotion approval, shipment record, retailer remittance, deduction detail, proof of performance, credit memo, and customer ledger','A retailer remits $86,000 against $100,000 of invoices. The deduction file shows $8,000 of approved promotion allowances, $3,500 of slotting fees, and $2,500 of shortages. Shipping evidence contradicts $1,200 of the shortage claim, which remains open instead of being netted into sales.','trade-agreement interpretation, promotion eligibility, shortage responsibility, food compliance, credit approval, or revenue presentation','sales operations owner and manufacturing controller',[['FDA food industry guidance','https://www.fda.gov/food/guidance-documents-regulatory-information-topic-food-and-dietary-supplements'],['FTC business guidance','https://www.ftc.gov/business-guidance']]],
  ['offshore-bookkeeping-architecture-phase-billing-reconciliation','Reconcile architecture phase billings to contract budgets and labor','Professional services bookkeeping','/thumbnails/offshore-bookkeeping-project-margin-bridge.webp','/services/management-reporting-support','architecture phase billing','executed agreement, phase budget, approved amendment, timesheet detail, consultant invoice, reimbursable expense, client invoice, receipt, and project ledger','A project budget assigns $45,000 to schematic design and $70,000 to design development. Labor reports show 92% of the first phase consumed, while billings show 100% and include a $6,000 consultant charge assigned to the next phase. The bridge isolates the phase and coding questions.','phase completion, scope interpretation, amendment approval, consultant responsibility, billing authorization, or revenue recognition','project principal and finance reviewer',[['AIA contract documents resources','https://www.aiacontracts.com/resources'],['U.S. Department of Labor recordkeeping','https://www.dol.gov/agencies/whd/fact-sheets/21-flsa-recordkeeping']]],
  ['offshore-bookkeeping-private-school-tuition-aid-rollforward','Roll forward private-school tuition, financial aid, deposits, and refunds','Education bookkeeping','/thumbnails/bookkeeping-customer-deposit-reconciliation.webp','/services/accounts-receivable-support','private-school tuition receivables','enrollment agreement, student roster, tuition schedule, aid approval, deposit receipt, billing file, withdrawals, refunds, cash receipts, and student ledger','Gross annual tuition for a cohort is $620,000. Approved aid totals $84,000, deposits are $58,000, and billing is $531,000. Two withdrawn students retain $9,500 of charges pending policy review. The rollforward identifies the $5,000 remaining difference without assuming its cause.','enrollment-contract interpretation, aid eligibility, withdrawal terms, refund approval, student privacy, or revenue recognition','registrar, financial-aid owner, and controller',[['U.S. Department of Education FERPA guidance','https://studentprivacy.ed.gov/ferpa'],['IRS recordkeeping guidance','https://www.irs.gov/businesses/small-businesses-self-employed/recordkeeping']]],
];

const shared = `Define the legal entity, period, cutoff, currency, systems, accounts, locations, preparer, and reviewer before downloading records. Save untouched source exports with extraction timestamps, filters, row counts, and control totals. If a source can change later, retain a version or dated copy. A missing record stays visible as an exception; it is not a reason to estimate a convenient value.

Start with the last reviewed balance. Show additions, applications, reversals, transfers, refunds, corrections, and the closing position on separate lines. Compare the schedule independently with the relevant operational report, subledger, general ledger, provider statement, and bank movement. Net cash can agree even when customer, vendor, liability, revenue, or expense detail is wrong.

Use one row for each traceable event. Record stable identifiers, effective date, service period, gross amount, deductions, fees, taxes, reserves, refunds, currency, evidence link, status, owner, and due date. Do not combine unrelated items because they share a deposit date. Preserve original and corrected values in separate fields and leave formulas visible.

Use exact statuses: ready to match, matched, timing item, missing evidence, amount mismatch, duplicate risk, policy question, awaiting approval, disputed, and closed with evidence. “Checking” is not useful unless it identifies the question, owner, and next date. Carry unresolved items forward with their original age and reference.

Protect access as carefully as the arithmetic. Use named accounts, multifactor authentication, and read-only or limited permissions where available. Separate preparation from payment release, bank-detail changes, credits, refunds, write-offs, journal posting, period locking, and deletion. Store sensitive evidence only in approved systems and mask identifiers when full details are unnecessary.

Test completeness in both directions. Select source records and trace them into the workpaper; then select workpaper lines and trace them back to original evidence. Reperform large, unusual, manual, old, zero-value, and post-cutoff items. Equal and opposite entries still require review because they can conceal duplicates or misdirection.

The reviewer confirms the population, control totals, formulas, exception ownership, proposed entries, and judgment calls. Each review note needs a focused question, owner, date, response, and closure evidence. Preserve earlier answers when they change so the file explains how the final treatment was reached.

Close with untouched exports, reconciliation, evidence index, exception log, approved entries, reviewer decisions, and a concise summary. State what tied, what remains open, the value exposed, the next owner, and the next review date. Link the package from the close checklist using a consistent entity-process-period-version name.`;

function render(a) {
  const [slug,title,category,image,service,subject,evidence,example,decision,reviewer,sources] = a;
  const paragraphs = shared.split('\n\n');
  return `---
title: "${title}"
description: "A practical offshore bookkeeping workflow for ${subject}, with source evidence, exception ownership, and clear review boundaries."
published: "${published}"
updated: "${published}"
category: "${category}"
type: "blog"
featuredImage: "${image}"
sources: ${JSON.stringify(sources.map(([name,url])=>({name,url})))}
takeaways: ["Reconcile the complete source population before investigating differences.","Give each exception evidence, an owner, a due date, and a focused decision request.","Keep approvals and accounting judgment with the authorized company reviewer."]
faqs: [["Can an offshore bookkeeper prepare this reconciliation?","Yes. A bookkeeper can gather authorized records, perform documented comparisons, maintain the exception queue, and prepare a review-ready handoff."],["What stays with the company reviewer?","Contract interpretation, accounting policy, approvals, legal conclusions, write-offs, and other judgment calls remain with the authorized owner or professional adviser."]]
---
Published September 23, 2026. This guide covers bookkeeping preparation and review support. It is not accounting, tax, legal, payroll, medical, investment, or regulatory advice.

## Why ${subject} needs its own workpaper

The records for ${subject} rarely arrive in one place or at one time. A reliable packet connects the ${evidence}. Posting the final bank amount alone removes the evidence needed to explain timing, fees, adjustments, ownership, and unresolved differences.

Authoritative background includes [${sources[0][0]}](${sources[0][1]}) and [${sources[1][0]}](${sources[1][1]}). These sources inform the workflow but do not replace the company’s contract, accounting policy, jurisdiction-specific rules, or professional advice. Record the source version and access date when a changing rule affects the procedure.

## Define the population and control totals

${paragraphs.slice(0,3).join('\n\n')}

## Work through a concrete example

${example}

The point is not to force the sources to agree. First reproduce each source’s arithmetic. Then compare the result with the approved contract or procedure. Finally show the ledger effect. Write exceptions as observed facts: one source reports a value, another reports a different value, and the difference is quantified. Possible causes belong in a separate note until evidence confirms them.

Set escalation thresholds under company policy, but do not use dollars as the only trigger. A small repeated error, an approaching dispute deadline, an access concern, altered payment details, or a missing approval may need immediate attention. Aging matters too: a modest item open for several months can reveal a broken handoff.

## Keep preparation separate from judgment

An offshore bookkeeper can download approved reports, compare identifiers and amounts, reperform arithmetic, request missing documents, update statuses, and draft an entry for review. The bookkeeper stops when the work requires ${decision}. That belongs to the ${reviewer}.

Make the decision request answerable without rebuilding the file. Include the amount, affected period, deadline, source links, observed difference, available options, and operational consequence of delay. Store the response with the workpaper rather than relying on a private message.

${paragraphs.slice(3,5).join('\n\n')}

## Review in both directions

${paragraphs.slice(5,7).join('\n\n')}

Track population count, matched and unmatched values, oldest exception, corrections returned, and percentage reviewed by deadline. These are workflow signals, not promises of financial performance. Repeated exceptions should lead to a better intake form, export, naming convention, or approval path.

## Close without hiding open items

${paragraphs.slice(7).join('\n\n')}

For help defining the preparation lane, see [the relevant Offshore Bookkeepers service](${service}). If your company needs a Philippines-based bookkeeper to maintain the schedule and route exceptions while your finance owner retains approval, [plan the role with Offshore Bookkeepers](/contact-us).
`;
}

const manifest = [];
for (const article of articles) {
  const [slug,title,category,image,,, ,,, ,sources] = article;
  const sourcePath = `content/blog/${slug}.md`;
  if (fs.existsSync(sourcePath) && !process.env.ALLOW_ROUTINE_REGEN) throw new Error(`Refusing to overwrite existing article: ${sourcePath}`);
  const body = render(article);
  fs.writeFileSync(sourcePath, body);
  manifest.push({family:category,topic:title,title,slug,route:`/blog/${slug}`,canonical:`https://offshorebookkeepers.com/blog/${slug}`,sourcePath,featuredImage:image,sources:sources.map(([name,url])=>({name,url})),publicationDate:published,status:process.env.CONTENT_COMMIT?'validated':'prepared',contentHash:crypto.createHash('sha256').update(body).digest('hex'),wordCount:(body.match(/\b[\w’'-]+\b/g)||[]).length,...(process.env.CONTENT_COMMIT?{contentCommit:process.env.CONTENT_COMMIT}:{})});
}
fs.mkdirSync(`.paperclip/daily-content/${published}`,{recursive:true});
fs.writeFileSync(`.paperclip/daily-content/${published}/blog-off-74.json`,JSON.stringify(manifest,null,2)+'\n');
console.log(`Created ${manifest.length} OFF-74 articles.`);
